// Code generated by ent, DO NOT EDIT.

package vcontestparticipant

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the vcontestparticipant type in the database.
	Label = "vcontest_participant"
	// FieldContestID holds the string denoting the contest_id field in the database.
	FieldContestID = "contest_id"
	// FieldTeamID holds the string denoting the team_id field in the database.
	FieldTeamID = "team_id"
	// FieldBestPlace holds the string denoting the best_place field in the database.
	FieldBestPlace = "best_place"
	// Table holds the table name of the vcontestparticipant in the database.
	Table = "vcontest_participants"
)

// Columns holds all SQL columns for vcontestparticipant fields.
var Columns = []string{
	FieldContestID,
	FieldTeamID,
	FieldBestPlace,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the VContestParticipant queries.
type OrderOption func(*sql.Selector)

// ByContestID orders the results by the contest_id field.
func ByContestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContestID, opts...).ToFunc()
}

// ByTeamID orders the results by the team_id field.
func ByTeamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamID, opts...).ToFunc()
}

// ByBestPlace orders the results by the best_place field.
func ByBestPlace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBestPlace, opts...).ToFunc()
}
