// Code generated by ent, DO NOT EDIT.

package aggregateduserstatistics

import (
	"openctfbackend/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// TotalViews applies equality check predicate on the "total_views" field. It's identical to TotalViewsEQ.
func TotalViews(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldEQ(FieldTotalViews, v))
}

// WriteupsAuthored applies equality check predicate on the "writeups_authored" field. It's identical to WriteupsAuthoredEQ.
func WriteupsAuthored(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldEQ(FieldWriteupsAuthored, v))
}

// ContestsParticipated applies equality check predicate on the "contests_participated" field. It's identical to ContestsParticipatedEQ.
func ContestsParticipated(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldEQ(FieldContestsParticipated, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldEQ(FieldUserID, v))
}

// TotalViewsEQ applies the EQ predicate on the "total_views" field.
func TotalViewsEQ(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldEQ(FieldTotalViews, v))
}

// TotalViewsNEQ applies the NEQ predicate on the "total_views" field.
func TotalViewsNEQ(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldNEQ(FieldTotalViews, v))
}

// TotalViewsIn applies the In predicate on the "total_views" field.
func TotalViewsIn(vs ...int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldIn(FieldTotalViews, vs...))
}

// TotalViewsNotIn applies the NotIn predicate on the "total_views" field.
func TotalViewsNotIn(vs ...int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldNotIn(FieldTotalViews, vs...))
}

// TotalViewsGT applies the GT predicate on the "total_views" field.
func TotalViewsGT(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldGT(FieldTotalViews, v))
}

// TotalViewsGTE applies the GTE predicate on the "total_views" field.
func TotalViewsGTE(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldGTE(FieldTotalViews, v))
}

// TotalViewsLT applies the LT predicate on the "total_views" field.
func TotalViewsLT(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldLT(FieldTotalViews, v))
}

// TotalViewsLTE applies the LTE predicate on the "total_views" field.
func TotalViewsLTE(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldLTE(FieldTotalViews, v))
}

// WriteupsAuthoredEQ applies the EQ predicate on the "writeups_authored" field.
func WriteupsAuthoredEQ(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldEQ(FieldWriteupsAuthored, v))
}

// WriteupsAuthoredNEQ applies the NEQ predicate on the "writeups_authored" field.
func WriteupsAuthoredNEQ(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldNEQ(FieldWriteupsAuthored, v))
}

// WriteupsAuthoredIn applies the In predicate on the "writeups_authored" field.
func WriteupsAuthoredIn(vs ...int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldIn(FieldWriteupsAuthored, vs...))
}

// WriteupsAuthoredNotIn applies the NotIn predicate on the "writeups_authored" field.
func WriteupsAuthoredNotIn(vs ...int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldNotIn(FieldWriteupsAuthored, vs...))
}

// WriteupsAuthoredGT applies the GT predicate on the "writeups_authored" field.
func WriteupsAuthoredGT(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldGT(FieldWriteupsAuthored, v))
}

// WriteupsAuthoredGTE applies the GTE predicate on the "writeups_authored" field.
func WriteupsAuthoredGTE(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldGTE(FieldWriteupsAuthored, v))
}

// WriteupsAuthoredLT applies the LT predicate on the "writeups_authored" field.
func WriteupsAuthoredLT(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldLT(FieldWriteupsAuthored, v))
}

// WriteupsAuthoredLTE applies the LTE predicate on the "writeups_authored" field.
func WriteupsAuthoredLTE(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldLTE(FieldWriteupsAuthored, v))
}

// ContestsParticipatedEQ applies the EQ predicate on the "contests_participated" field.
func ContestsParticipatedEQ(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldEQ(FieldContestsParticipated, v))
}

// ContestsParticipatedNEQ applies the NEQ predicate on the "contests_participated" field.
func ContestsParticipatedNEQ(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldNEQ(FieldContestsParticipated, v))
}

// ContestsParticipatedIn applies the In predicate on the "contests_participated" field.
func ContestsParticipatedIn(vs ...int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldIn(FieldContestsParticipated, vs...))
}

// ContestsParticipatedNotIn applies the NotIn predicate on the "contests_participated" field.
func ContestsParticipatedNotIn(vs ...int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldNotIn(FieldContestsParticipated, vs...))
}

// ContestsParticipatedGT applies the GT predicate on the "contests_participated" field.
func ContestsParticipatedGT(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldGT(FieldContestsParticipated, v))
}

// ContestsParticipatedGTE applies the GTE predicate on the "contests_participated" field.
func ContestsParticipatedGTE(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldGTE(FieldContestsParticipated, v))
}

// ContestsParticipatedLT applies the LT predicate on the "contests_participated" field.
func ContestsParticipatedLT(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldLT(FieldContestsParticipated, v))
}

// ContestsParticipatedLTE applies the LTE predicate on the "contests_participated" field.
func ContestsParticipatedLTE(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldLTE(FieldContestsParticipated, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.FieldLTE(FieldUserID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AggregatedUserStatistics) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AggregatedUserStatistics) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AggregatedUserStatistics) predicate.AggregatedUserStatistics {
	return predicate.AggregatedUserStatistics(sql.NotPredicates(p))
}
