// Code generated by ent, DO NOT EDIT.

package aggregatedcontest

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the aggregatedcontest type in the database.
	Label = "aggregated_contest"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldRules holds the string denoting the rules field in the database.
	FieldRules = "rules"
	// FieldPrizes holds the string denoting the prizes field in the database.
	FieldPrizes = "prizes"
	// FieldStart holds the string denoting the start field in the database.
	FieldStart = "start"
	// FieldEnd holds the string denoting the end field in the database.
	FieldEnd = "end"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldCtftimeID holds the string denoting the ctftime_id field in the database.
	FieldCtftimeID = "ctftime_id"
	// FieldAssignedWeightPoints holds the string denoting the assigned_weight_points field in the database.
	FieldAssignedWeightPoints = "assigned_weight_points"
	// FieldLogoURL holds the string denoting the logo_url field in the database.
	FieldLogoURL = "logo_url"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldParticipants holds the string denoting the participants field in the database.
	FieldParticipants = "participants"
	// Table holds the table name of the aggregatedcontest in the database.
	Table = "aggregated_contests"
)

// Columns holds all SQL columns for aggregatedcontest fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldRules,
	FieldPrizes,
	FieldStart,
	FieldEnd,
	FieldDuration,
	FieldURL,
	FieldCtftimeID,
	FieldAssignedWeightPoints,
	FieldLogoURL,
	FieldRating,
	FieldParticipants,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultAssignedWeightPoints holds the default value on creation for the "assigned_weight_points" field.
	DefaultAssignedWeightPoints int
)

// OrderOption defines the ordering options for the AggregatedContest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByRules orders the results by the rules field.
func ByRules(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRules, opts...).ToFunc()
}

// ByPrizes orders the results by the prizes field.
func ByPrizes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizes, opts...).ToFunc()
}

// ByStart orders the results by the start field.
func ByStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStart, opts...).ToFunc()
}

// ByEnd orders the results by the end field.
func ByEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnd, opts...).ToFunc()
}

// ByDuration orders the results by the duration field.
func ByDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDuration, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByCtftimeID orders the results by the ctftime_id field.
func ByCtftimeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCtftimeID, opts...).ToFunc()
}

// ByAssignedWeightPoints orders the results by the assigned_weight_points field.
func ByAssignedWeightPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedWeightPoints, opts...).ToFunc()
}

// ByLogoURL orders the results by the logo_url field.
func ByLogoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogoURL, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByParticipants orders the results by the participants field.
func ByParticipants(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParticipants, opts...).ToFunc()
}
