// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"openctfbackend/ent/aggregatedcontest"
	"openctfbackend/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// AggregatedContestQuery is the builder for querying AggregatedContest entities.
type AggregatedContestQuery struct {
	config
	ctx        *QueryContext
	order      []aggregatedcontest.OrderOption
	inters     []Interceptor
	predicates []predicate.AggregatedContest
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AggregatedContestQuery builder.
func (_q *AggregatedContestQuery) Where(ps ...predicate.AggregatedContest) *AggregatedContestQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AggregatedContestQuery) Limit(limit int) *AggregatedContestQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AggregatedContestQuery) Offset(offset int) *AggregatedContestQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AggregatedContestQuery) Unique(unique bool) *AggregatedContestQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AggregatedContestQuery) Order(o ...aggregatedcontest.OrderOption) *AggregatedContestQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first AggregatedContest entity from the query.
// Returns a *NotFoundError when no AggregatedContest was found.
func (_q *AggregatedContestQuery) First(ctx context.Context) (*AggregatedContest, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{aggregatedcontest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AggregatedContestQuery) FirstX(ctx context.Context) *AggregatedContest {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single AggregatedContest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AggregatedContest entity is found.
// Returns a *NotFoundError when no AggregatedContest entities are found.
func (_q *AggregatedContestQuery) Only(ctx context.Context) (*AggregatedContest, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{aggregatedcontest.Label}
	default:
		return nil, &NotSingularError{aggregatedcontest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AggregatedContestQuery) OnlyX(ctx context.Context) *AggregatedContest {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of AggregatedContests.
func (_q *AggregatedContestQuery) All(ctx context.Context) ([]*AggregatedContest, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AggregatedContest, *AggregatedContestQuery]()
	return withInterceptors[[]*AggregatedContest](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AggregatedContestQuery) AllX(ctx context.Context) []*AggregatedContest {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (_q *AggregatedContestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AggregatedContestQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AggregatedContestQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AggregatedContestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AggregatedContestQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AggregatedContestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AggregatedContestQuery) Clone() *AggregatedContestQuery {
	if _q == nil {
		return nil
	}
	return &AggregatedContestQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]aggregatedcontest.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.AggregatedContest{}, _q.predicates...),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ID int `json:"id"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AggregatedContest.Query().
//		GroupBy(aggregatedcontest.FieldID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AggregatedContestQuery) GroupBy(field string, fields ...string) *AggregatedContestGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AggregatedContestGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = aggregatedcontest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ID int `json:"id"`
//	}
//
//	client.AggregatedContest.Query().
//		Select(aggregatedcontest.FieldID).
//		Scan(ctx, &v)
func (_q *AggregatedContestQuery) Select(fields ...string) *AggregatedContestSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AggregatedContestSelect{AggregatedContestQuery: _q}
	sbuild.label = aggregatedcontest.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AggregatedContestSelect configured with the given aggregations.
func (_q *AggregatedContestQuery) Aggregate(fns ...AggregateFunc) *AggregatedContestSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AggregatedContestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !aggregatedcontest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AggregatedContestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AggregatedContest, error) {
	var (
		nodes = []*AggregatedContest{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AggregatedContest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AggregatedContest{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (_q *AggregatedContestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AggregatedContestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(aggregatedcontest.Table, aggregatedcontest.Columns, nil)
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AggregatedContestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(aggregatedcontest.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = aggregatedcontest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AggregatedContestGroupBy is the group-by builder for AggregatedContest entities.
type AggregatedContestGroupBy struct {
	selector
	build *AggregatedContestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AggregatedContestGroupBy) Aggregate(fns ...AggregateFunc) *AggregatedContestGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AggregatedContestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AggregatedContestQuery, *AggregatedContestGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AggregatedContestGroupBy) sqlScan(ctx context.Context, root *AggregatedContestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AggregatedContestSelect is the builder for selecting fields of AggregatedContest entities.
type AggregatedContestSelect struct {
	*AggregatedContestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AggregatedContestSelect) Aggregate(fns ...AggregateFunc) *AggregatedContestSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AggregatedContestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AggregatedContestQuery, *AggregatedContestSelect](ctx, _s.AggregatedContestQuery, _s, _s.inters, v)
}

func (_s *AggregatedContestSelect) sqlScan(ctx context.Context, root *AggregatedContestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
