// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"openctfbackend/ent/aggregateduserstatistics"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AggregatedUserStatistics is the model entity for the AggregatedUserStatistics schema.
type AggregatedUserStatistics struct {
	config `json:"-"`
	// TotalViews holds the value of the "total_views" field.
	TotalViews int `json:"total_views"`
	// WriteupsAuthored holds the value of the "writeups_authored" field.
	WriteupsAuthored int `json:"writeups_authored"`
	// ContestsParticipated holds the value of the "contests_participated" field.
	ContestsParticipated int `json:"contests_participated"`
	// UserID holds the value of the "user_id" field.
	UserID       int `json:"user_id"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AggregatedUserStatistics) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aggregateduserstatistics.FieldTotalViews, aggregateduserstatistics.FieldWriteupsAuthored, aggregateduserstatistics.FieldContestsParticipated, aggregateduserstatistics.FieldUserID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AggregatedUserStatistics fields.
func (_m *AggregatedUserStatistics) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aggregateduserstatistics.FieldTotalViews:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_views", values[i])
			} else if value.Valid {
				_m.TotalViews = int(value.Int64)
			}
		case aggregateduserstatistics.FieldWriteupsAuthored:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field writeups_authored", values[i])
			} else if value.Valid {
				_m.WriteupsAuthored = int(value.Int64)
			}
		case aggregateduserstatistics.FieldContestsParticipated:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field contests_participated", values[i])
			} else if value.Valid {
				_m.ContestsParticipated = int(value.Int64)
			}
		case aggregateduserstatistics.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AggregatedUserStatistics.
// This includes values selected through modifiers, order, etc.
func (_m *AggregatedUserStatistics) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Unwrap unwraps the AggregatedUserStatistics entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AggregatedUserStatistics) Unwrap() *AggregatedUserStatistics {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AggregatedUserStatistics is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AggregatedUserStatistics) String() string {
	var builder strings.Builder
	builder.WriteString("AggregatedUserStatistics(")
	builder.WriteString("total_views=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalViews))
	builder.WriteString(", ")
	builder.WriteString("writeups_authored=")
	builder.WriteString(fmt.Sprintf("%v", _m.WriteupsAuthored))
	builder.WriteString(", ")
	builder.WriteString("contests_participated=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContestsParticipated))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// AggregatedUserStatisticsSlice is a parsable slice of AggregatedUserStatistics.
type AggregatedUserStatisticsSlice []*AggregatedUserStatistics
