// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"openctfbackend/ent/aggregatedcontestsdifficulty"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AggregatedContestsDifficulty is the model entity for the AggregatedContestsDifficulty schema.
type AggregatedContestsDifficulty struct {
	config `json:"-"`
	// ContestID holds the value of the "contest_id" field.
	ContestID int `json:"contest_id"`
	// ContestName holds the value of the "contest_name" field.
	ContestName string `json:"contest_name"`
	// End holds the value of the "end" field.
	End time.Time `json:"end"`
	// AssignedWeightPoints holds the value of the "assigned_weight_points" field.
	AssignedWeightPoints int `json:"assigned_weight_points"`
	// OrganizersID holds the value of the "organizers_id" field.
	OrganizersID int `json:"organizers_id"`
	// AvgDifficulty holds the value of the "avg_difficulty" field.
	AvgDifficulty float64 `json:"avg_difficulty"`
	// AvgQuality holds the value of the "avg_quality" field.
	AvgQuality float64 `json:"avg_quality"`
	// Participants holds the value of the "participants" field.
	Participants int `json:"participants"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AggregatedContestsDifficulty) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aggregatedcontestsdifficulty.FieldAvgDifficulty, aggregatedcontestsdifficulty.FieldAvgQuality:
			values[i] = new(sql.NullFloat64)
		case aggregatedcontestsdifficulty.FieldContestID, aggregatedcontestsdifficulty.FieldAssignedWeightPoints, aggregatedcontestsdifficulty.FieldOrganizersID, aggregatedcontestsdifficulty.FieldParticipants:
			values[i] = new(sql.NullInt64)
		case aggregatedcontestsdifficulty.FieldContestName:
			values[i] = new(sql.NullString)
		case aggregatedcontestsdifficulty.FieldEnd:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AggregatedContestsDifficulty fields.
func (_m *AggregatedContestsDifficulty) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aggregatedcontestsdifficulty.FieldContestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field contest_id", values[i])
			} else if value.Valid {
				_m.ContestID = int(value.Int64)
			}
		case aggregatedcontestsdifficulty.FieldContestName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contest_name", values[i])
			} else if value.Valid {
				_m.ContestName = value.String
			}
		case aggregatedcontestsdifficulty.FieldEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end", values[i])
			} else if value.Valid {
				_m.End = value.Time
			}
		case aggregatedcontestsdifficulty.FieldAssignedWeightPoints:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_weight_points", values[i])
			} else if value.Valid {
				_m.AssignedWeightPoints = int(value.Int64)
			}
		case aggregatedcontestsdifficulty.FieldOrganizersID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field organizers_id", values[i])
			} else if value.Valid {
				_m.OrganizersID = int(value.Int64)
			}
		case aggregatedcontestsdifficulty.FieldAvgDifficulty:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field avg_difficulty", values[i])
			} else if value.Valid {
				_m.AvgDifficulty = value.Float64
			}
		case aggregatedcontestsdifficulty.FieldAvgQuality:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field avg_quality", values[i])
			} else if value.Valid {
				_m.AvgQuality = value.Float64
			}
		case aggregatedcontestsdifficulty.FieldParticipants:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field participants", values[i])
			} else if value.Valid {
				_m.Participants = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AggregatedContestsDifficulty.
// This includes values selected through modifiers, order, etc.
func (_m *AggregatedContestsDifficulty) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Unwrap unwraps the AggregatedContestsDifficulty entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AggregatedContestsDifficulty) Unwrap() *AggregatedContestsDifficulty {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AggregatedContestsDifficulty is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AggregatedContestsDifficulty) String() string {
	var builder strings.Builder
	builder.WriteString("AggregatedContestsDifficulty(")
	builder.WriteString("contest_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContestID))
	builder.WriteString(", ")
	builder.WriteString("contest_name=")
	builder.WriteString(_m.ContestName)
	builder.WriteString(", ")
	builder.WriteString("end=")
	builder.WriteString(_m.End.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("assigned_weight_points=")
	builder.WriteString(fmt.Sprintf("%v", _m.AssignedWeightPoints))
	builder.WriteString(", ")
	builder.WriteString("organizers_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrganizersID))
	builder.WriteString(", ")
	builder.WriteString("avg_difficulty=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvgDifficulty))
	builder.WriteString(", ")
	builder.WriteString("avg_quality=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvgQuality))
	builder.WriteString(", ")
	builder.WriteString("participants=")
	builder.WriteString(fmt.Sprintf("%v", _m.Participants))
	builder.WriteByte(')')
	return builder.String()
}

// AggregatedContestsDifficulties is a parsable slice of AggregatedContestsDifficulty.
type AggregatedContestsDifficulties []*AggregatedContestsDifficulty
