// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"openctfbackend/ent/aggregatedteamsdetails"
	"openctfbackend/ent/schema"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AggregatedTeamsDetails is the model entity for the AggregatedTeamsDetails schema.
type AggregatedTeamsDetails struct {
	config `json:"-"`
	// ID holds the value of the "id" field.
	ID int `json:"id"`
	// Name holds the value of the "name" field.
	Name string `json:"name"`
	// Description holds the value of the "description" field.
	Description *string `json:"description"`
	// CtftimeID holds the value of the "ctftime_id" field.
	CtftimeID *int `json:"ctftime_id"`
	// CtftimeVerifiedAt holds the value of the "ctftime_verified_at" field.
	CtftimeVerifiedAt *time.Time `json:"ctftime_verified_at"`
	// VerifiedAt holds the value of the "verified_at" field.
	VerifiedAt *time.Time `json:"verified_at"`
	// CountryCode holds the value of the "country_code" field.
	CountryCode string `json:"country_code"`
	// TeamLogoURL holds the value of the "team_logo_url" field.
	TeamLogoURL *string `json:"team_logo_url"`
	// BannerImageURL holds the value of the "banner_image_url" field.
	BannerImageURL *string `json:"banner_image_url"`
	// DiscordURL holds the value of the "discord_url" field.
	DiscordURL *string `json:"discord_url"`
	// GithubURL holds the value of the "github_url" field.
	GithubURL *string `json:"github_url"`
	// Recruiting holds the value of the "recruiting" field.
	Recruiting bool `json:"recruiting"`
	// ContactInfo holds the value of the "contact_info" field.
	ContactInfo *string `json:"contact_info"`
	// LookingFor holds the value of the "looking_for" field.
	LookingFor []string `json:"looking_for"`
	// WebsiteURL holds the value of the "website_url" field.
	WebsiteURL *string `json:"website_url"`
	// AvgPlace holds the value of the "avg_place" field.
	AvgPlace *float64 `json:"avg_place"`
	// YearsActive holds the value of the "years_active" field.
	YearsActive int `json:"years_active"`
	// ContestHistory holds the value of the "contest_history" field.
	ContestHistory []schema.TeamsDetailsContest `json:"contest_history"`
	// Achievements holds the value of the "achievements" field.
	Achievements []schema.TeamsDetailsAchievement `json:"achievements"`
	// Members holds the value of the "members" field.
	Members []schema.TeamsDetailsUser `json:"members"`
	// Captain holds the value of the "captain" field.
	Captain schema.TeamsDetailsUser `json:"captain"`
	// VerifiedBy holds the value of the "verified_by" field.
	VerifiedBy   schema.TeamsDetailsUser `json:"verified_by"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AggregatedTeamsDetails) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aggregatedteamsdetails.FieldLookingFor, aggregatedteamsdetails.FieldContestHistory, aggregatedteamsdetails.FieldAchievements, aggregatedteamsdetails.FieldMembers, aggregatedteamsdetails.FieldCaptain, aggregatedteamsdetails.FieldVerifiedBy:
			values[i] = new([]byte)
		case aggregatedteamsdetails.FieldRecruiting:
			values[i] = new(sql.NullBool)
		case aggregatedteamsdetails.FieldAvgPlace:
			values[i] = new(sql.NullFloat64)
		case aggregatedteamsdetails.FieldID, aggregatedteamsdetails.FieldCtftimeID, aggregatedteamsdetails.FieldYearsActive:
			values[i] = new(sql.NullInt64)
		case aggregatedteamsdetails.FieldName, aggregatedteamsdetails.FieldDescription, aggregatedteamsdetails.FieldCountryCode, aggregatedteamsdetails.FieldTeamLogoURL, aggregatedteamsdetails.FieldBannerImageURL, aggregatedteamsdetails.FieldDiscordURL, aggregatedteamsdetails.FieldGithubURL, aggregatedteamsdetails.FieldContactInfo, aggregatedteamsdetails.FieldWebsiteURL:
			values[i] = new(sql.NullString)
		case aggregatedteamsdetails.FieldCtftimeVerifiedAt, aggregatedteamsdetails.FieldVerifiedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AggregatedTeamsDetails fields.
func (_m *AggregatedTeamsDetails) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aggregatedteamsdetails.FieldID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = int(value.Int64)
			}
		case aggregatedteamsdetails.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case aggregatedteamsdetails.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case aggregatedteamsdetails.FieldCtftimeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ctftime_id", values[i])
			} else if value.Valid {
				_m.CtftimeID = new(int)
				*_m.CtftimeID = int(value.Int64)
			}
		case aggregatedteamsdetails.FieldCtftimeVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ctftime_verified_at", values[i])
			} else if value.Valid {
				_m.CtftimeVerifiedAt = new(time.Time)
				*_m.CtftimeVerifiedAt = value.Time
			}
		case aggregatedteamsdetails.FieldVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field verified_at", values[i])
			} else if value.Valid {
				_m.VerifiedAt = new(time.Time)
				*_m.VerifiedAt = value.Time
			}
		case aggregatedteamsdetails.FieldCountryCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country_code", values[i])
			} else if value.Valid {
				_m.CountryCode = value.String
			}
		case aggregatedteamsdetails.FieldTeamLogoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field team_logo_url", values[i])
			} else if value.Valid {
				_m.TeamLogoURL = new(string)
				*_m.TeamLogoURL = value.String
			}
		case aggregatedteamsdetails.FieldBannerImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field banner_image_url", values[i])
			} else if value.Valid {
				_m.BannerImageURL = new(string)
				*_m.BannerImageURL = value.String
			}
		case aggregatedteamsdetails.FieldDiscordURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field discord_url", values[i])
			} else if value.Valid {
				_m.DiscordURL = new(string)
				*_m.DiscordURL = value.String
			}
		case aggregatedteamsdetails.FieldGithubURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field github_url", values[i])
			} else if value.Valid {
				_m.GithubURL = new(string)
				*_m.GithubURL = value.String
			}
		case aggregatedteamsdetails.FieldRecruiting:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field recruiting", values[i])
			} else if value.Valid {
				_m.Recruiting = value.Bool
			}
		case aggregatedteamsdetails.FieldContactInfo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_info", values[i])
			} else if value.Valid {
				_m.ContactInfo = new(string)
				*_m.ContactInfo = value.String
			}
		case aggregatedteamsdetails.FieldLookingFor:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field looking_for", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.LookingFor); err != nil {
					return fmt.Errorf("unmarshal field looking_for: %w", err)
				}
			}
		case aggregatedteamsdetails.FieldWebsiteURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field website_url", values[i])
			} else if value.Valid {
				_m.WebsiteURL = new(string)
				*_m.WebsiteURL = value.String
			}
		case aggregatedteamsdetails.FieldAvgPlace:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field avg_place", values[i])
			} else if value.Valid {
				_m.AvgPlace = new(float64)
				*_m.AvgPlace = value.Float64
			}
		case aggregatedteamsdetails.FieldYearsActive:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field years_active", values[i])
			} else if value.Valid {
				_m.YearsActive = int(value.Int64)
			}
		case aggregatedteamsdetails.FieldContestHistory:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field contest_history", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ContestHistory); err != nil {
					return fmt.Errorf("unmarshal field contest_history: %w", err)
				}
			}
		case aggregatedteamsdetails.FieldAchievements:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field achievements", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Achievements); err != nil {
					return fmt.Errorf("unmarshal field achievements: %w", err)
				}
			}
		case aggregatedteamsdetails.FieldMembers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field members", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Members); err != nil {
					return fmt.Errorf("unmarshal field members: %w", err)
				}
			}
		case aggregatedteamsdetails.FieldCaptain:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field captain", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Captain); err != nil {
					return fmt.Errorf("unmarshal field captain: %w", err)
				}
			}
		case aggregatedteamsdetails.FieldVerifiedBy:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field verified_by", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.VerifiedBy); err != nil {
					return fmt.Errorf("unmarshal field verified_by: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AggregatedTeamsDetails.
// This includes values selected through modifiers, order, etc.
func (_m *AggregatedTeamsDetails) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Unwrap unwraps the AggregatedTeamsDetails entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AggregatedTeamsDetails) Unwrap() *AggregatedTeamsDetails {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AggregatedTeamsDetails is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AggregatedTeamsDetails) String() string {
	var builder strings.Builder
	builder.WriteString("AggregatedTeamsDetails(")
	builder.WriteString("id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CtftimeID; v != nil {
		builder.WriteString("ctftime_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CtftimeVerifiedAt; v != nil {
		builder.WriteString("ctftime_verified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.VerifiedAt; v != nil {
		builder.WriteString("verified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("country_code=")
	builder.WriteString(_m.CountryCode)
	builder.WriteString(", ")
	if v := _m.TeamLogoURL; v != nil {
		builder.WriteString("team_logo_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BannerImageURL; v != nil {
		builder.WriteString("banner_image_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DiscordURL; v != nil {
		builder.WriteString("discord_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GithubURL; v != nil {
		builder.WriteString("github_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("recruiting=")
	builder.WriteString(fmt.Sprintf("%v", _m.Recruiting))
	builder.WriteString(", ")
	if v := _m.ContactInfo; v != nil {
		builder.WriteString("contact_info=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("looking_for=")
	builder.WriteString(fmt.Sprintf("%v", _m.LookingFor))
	builder.WriteString(", ")
	if v := _m.WebsiteURL; v != nil {
		builder.WriteString("website_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AvgPlace; v != nil {
		builder.WriteString("avg_place=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("years_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.YearsActive))
	builder.WriteString(", ")
	builder.WriteString("contest_history=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContestHistory))
	builder.WriteString(", ")
	builder.WriteString("achievements=")
	builder.WriteString(fmt.Sprintf("%v", _m.Achievements))
	builder.WriteString(", ")
	builder.WriteString("members=")
	builder.WriteString(fmt.Sprintf("%v", _m.Members))
	builder.WriteString(", ")
	builder.WriteString("captain=")
	builder.WriteString(fmt.Sprintf("%v", _m.Captain))
	builder.WriteString(", ")
	builder.WriteString("verified_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.VerifiedBy))
	builder.WriteByte(')')
	return builder.String()
}

// AggregatedTeamsDetailsSlice is a parsable slice of AggregatedTeamsDetails.
type AggregatedTeamsDetailsSlice []*AggregatedTeamsDetails
