// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"openctfbackend/ent/contestrating"
	"openctfbackend/ent/predicate"
	"openctfbackend/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContestRatingQuery is the builder for querying ContestRating entities.
type ContestRatingQuery struct {
	config
	ctx         *QueryContext
	order       []contestrating.OrderOption
	inters      []Interceptor
	predicates  []predicate.ContestRating
	withUser    *UserQuery
	withContest *UserQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ContestRatingQuery builder.
func (crq *ContestRatingQuery) Where(ps ...predicate.ContestRating) *ContestRatingQuery {
	crq.predicates = append(crq.predicates, ps...)
	return crq
}

// Limit the number of records to be returned by this query.
func (crq *ContestRatingQuery) Limit(limit int) *ContestRatingQuery {
	crq.ctx.Limit = &limit
	return crq
}

// Offset to start from.
func (crq *ContestRatingQuery) Offset(offset int) *ContestRatingQuery {
	crq.ctx.Offset = &offset
	return crq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (crq *ContestRatingQuery) Unique(unique bool) *ContestRatingQuery {
	crq.ctx.Unique = &unique
	return crq
}

// Order specifies how the records should be ordered.
func (crq *ContestRatingQuery) Order(o ...contestrating.OrderOption) *ContestRatingQuery {
	crq.order = append(crq.order, o...)
	return crq
}

// QueryUser chains the current query on the "user" edge.
func (crq *ContestRatingQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contestrating.Table, contestrating.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, contestrating.UserTable, contestrating.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryContest chains the current query on the "contest" edge.
func (crq *ContestRatingQuery) QueryContest() *UserQuery {
	query := (&UserClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contestrating.Table, contestrating.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, contestrating.ContestTable, contestrating.ContestColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ContestRating entity from the query.
// Returns a *NotFoundError when no ContestRating was found.
func (crq *ContestRatingQuery) First(ctx context.Context) (*ContestRating, error) {
	nodes, err := crq.Limit(1).All(setContextOp(ctx, crq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{contestrating.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (crq *ContestRatingQuery) FirstX(ctx context.Context) *ContestRating {
	node, err := crq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ContestRating ID from the query.
// Returns a *NotFoundError when no ContestRating ID was found.
func (crq *ContestRatingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = crq.Limit(1).IDs(setContextOp(ctx, crq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{contestrating.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (crq *ContestRatingQuery) FirstIDX(ctx context.Context) int {
	id, err := crq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ContestRating entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ContestRating entity is found.
// Returns a *NotFoundError when no ContestRating entities are found.
func (crq *ContestRatingQuery) Only(ctx context.Context) (*ContestRating, error) {
	nodes, err := crq.Limit(2).All(setContextOp(ctx, crq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{contestrating.Label}
	default:
		return nil, &NotSingularError{contestrating.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (crq *ContestRatingQuery) OnlyX(ctx context.Context) *ContestRating {
	node, err := crq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ContestRating ID in the query.
// Returns a *NotSingularError when more than one ContestRating ID is found.
// Returns a *NotFoundError when no entities are found.
func (crq *ContestRatingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = crq.Limit(2).IDs(setContextOp(ctx, crq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{contestrating.Label}
	default:
		err = &NotSingularError{contestrating.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (crq *ContestRatingQuery) OnlyIDX(ctx context.Context) int {
	id, err := crq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ContestRatings.
func (crq *ContestRatingQuery) All(ctx context.Context) ([]*ContestRating, error) {
	ctx = setContextOp(ctx, crq.ctx, ent.OpQueryAll)
	if err := crq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ContestRating, *ContestRatingQuery]()
	return withInterceptors[[]*ContestRating](ctx, crq, qr, crq.inters)
}

// AllX is like All, but panics if an error occurs.
func (crq *ContestRatingQuery) AllX(ctx context.Context) []*ContestRating {
	nodes, err := crq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ContestRating IDs.
func (crq *ContestRatingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if crq.ctx.Unique == nil && crq.path != nil {
		crq.Unique(true)
	}
	ctx = setContextOp(ctx, crq.ctx, ent.OpQueryIDs)
	if err = crq.Select(contestrating.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (crq *ContestRatingQuery) IDsX(ctx context.Context) []int {
	ids, err := crq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (crq *ContestRatingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, crq.ctx, ent.OpQueryCount)
	if err := crq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, crq, querierCount[*ContestRatingQuery](), crq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (crq *ContestRatingQuery) CountX(ctx context.Context) int {
	count, err := crq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (crq *ContestRatingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, crq.ctx, ent.OpQueryExist)
	switch _, err := crq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (crq *ContestRatingQuery) ExistX(ctx context.Context) bool {
	exist, err := crq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ContestRatingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (crq *ContestRatingQuery) Clone() *ContestRatingQuery {
	if crq == nil {
		return nil
	}
	return &ContestRatingQuery{
		config:      crq.config,
		ctx:         crq.ctx.Clone(),
		order:       append([]contestrating.OrderOption{}, crq.order...),
		inters:      append([]Interceptor{}, crq.inters...),
		predicates:  append([]predicate.ContestRating{}, crq.predicates...),
		withUser:    crq.withUser.Clone(),
		withContest: crq.withContest.Clone(),
		// clone intermediate query.
		sql:  crq.sql.Clone(),
		path: crq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *ContestRatingQuery) WithUser(opts ...func(*UserQuery)) *ContestRatingQuery {
	query := (&UserClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withUser = query
	return crq
}

// WithContest tells the query-builder to eager-load the nodes that are connected to
// the "contest" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *ContestRatingQuery) WithContest(opts ...func(*UserQuery)) *ContestRatingQuery {
	query := (&UserClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withContest = query
	return crq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Rating int `json:"rating,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ContestRating.Query().
//		GroupBy(contestrating.FieldRating).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (crq *ContestRatingQuery) GroupBy(field string, fields ...string) *ContestRatingGroupBy {
	crq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ContestRatingGroupBy{build: crq}
	grbuild.flds = &crq.ctx.Fields
	grbuild.label = contestrating.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Rating int `json:"rating,omitempty"`
//	}
//
//	client.ContestRating.Query().
//		Select(contestrating.FieldRating).
//		Scan(ctx, &v)
func (crq *ContestRatingQuery) Select(fields ...string) *ContestRatingSelect {
	crq.ctx.Fields = append(crq.ctx.Fields, fields...)
	sbuild := &ContestRatingSelect{ContestRatingQuery: crq}
	sbuild.label = contestrating.Label
	sbuild.flds, sbuild.scan = &crq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ContestRatingSelect configured with the given aggregations.
func (crq *ContestRatingQuery) Aggregate(fns ...AggregateFunc) *ContestRatingSelect {
	return crq.Select().Aggregate(fns...)
}

func (crq *ContestRatingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range crq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, crq); err != nil {
				return err
			}
		}
	}
	for _, f := range crq.ctx.Fields {
		if !contestrating.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if crq.path != nil {
		prev, err := crq.path(ctx)
		if err != nil {
			return err
		}
		crq.sql = prev
	}
	return nil
}

func (crq *ContestRatingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ContestRating, error) {
	var (
		nodes       = []*ContestRating{}
		withFKs     = crq.withFKs
		_spec       = crq.querySpec()
		loadedTypes = [2]bool{
			crq.withUser != nil,
			crq.withContest != nil,
		}
	)
	if crq.withUser != nil || crq.withContest != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, contestrating.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ContestRating).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ContestRating{config: crq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, crq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := crq.withUser; query != nil {
		if err := crq.loadUser(ctx, query, nodes, nil,
			func(n *ContestRating, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := crq.withContest; query != nil {
		if err := crq.loadContest(ctx, query, nodes, nil,
			func(n *ContestRating, e *User) { n.Edges.Contest = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (crq *ContestRatingQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*ContestRating, init func(*ContestRating), assign func(*ContestRating, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ContestRating)
	for i := range nodes {
		if nodes[i].contest_rating_user == nil {
			continue
		}
		fk := *nodes[i].contest_rating_user
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "contest_rating_user" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (crq *ContestRatingQuery) loadContest(ctx context.Context, query *UserQuery, nodes []*ContestRating, init func(*ContestRating), assign func(*ContestRating, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ContestRating)
	for i := range nodes {
		if nodes[i].contest_rating_contest == nil {
			continue
		}
		fk := *nodes[i].contest_rating_contest
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "contest_rating_contest" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (crq *ContestRatingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := crq.querySpec()
	_spec.Node.Columns = crq.ctx.Fields
	if len(crq.ctx.Fields) > 0 {
		_spec.Unique = crq.ctx.Unique != nil && *crq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, crq.driver, _spec)
}

func (crq *ContestRatingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(contestrating.Table, contestrating.Columns, sqlgraph.NewFieldSpec(contestrating.FieldID, field.TypeInt))
	_spec.From = crq.sql
	if unique := crq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if crq.path != nil {
		_spec.Unique = true
	}
	if fields := crq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contestrating.FieldID)
		for i := range fields {
			if fields[i] != contestrating.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := crq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := crq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := crq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := crq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (crq *ContestRatingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(crq.driver.Dialect())
	t1 := builder.Table(contestrating.Table)
	columns := crq.ctx.Fields
	if len(columns) == 0 {
		columns = contestrating.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if crq.sql != nil {
		selector = crq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if crq.ctx.Unique != nil && *crq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range crq.predicates {
		p(selector)
	}
	for _, p := range crq.order {
		p(selector)
	}
	if offset := crq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := crq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ContestRatingGroupBy is the group-by builder for ContestRating entities.
type ContestRatingGroupBy struct {
	selector
	build *ContestRatingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (crgb *ContestRatingGroupBy) Aggregate(fns ...AggregateFunc) *ContestRatingGroupBy {
	crgb.fns = append(crgb.fns, fns...)
	return crgb
}

// Scan applies the selector query and scans the result into the given value.
func (crgb *ContestRatingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crgb.build.ctx, ent.OpQueryGroupBy)
	if err := crgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContestRatingQuery, *ContestRatingGroupBy](ctx, crgb.build, crgb, crgb.build.inters, v)
}

func (crgb *ContestRatingGroupBy) sqlScan(ctx context.Context, root *ContestRatingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(crgb.fns))
	for _, fn := range crgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*crgb.flds)+len(crgb.fns))
		for _, f := range *crgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*crgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ContestRatingSelect is the builder for selecting fields of ContestRating entities.
type ContestRatingSelect struct {
	*ContestRatingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (crs *ContestRatingSelect) Aggregate(fns ...AggregateFunc) *ContestRatingSelect {
	crs.fns = append(crs.fns, fns...)
	return crs
}

// Scan applies the selector query and scans the result into the given value.
func (crs *ContestRatingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crs.ctx, ent.OpQuerySelect)
	if err := crs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContestRatingQuery, *ContestRatingSelect](ctx, crs.ContestRatingQuery, crs, crs.inters, v)
}

func (crs *ContestRatingSelect) sqlScan(ctx context.Context, root *ContestRatingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(crs.fns))
	for _, fn := range crs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*crs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
