// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"openctfbackend/ent/team"
	"openctfbackend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TeamCreate is the builder for creating a Team entity.
type TeamCreate struct {
	config
	mutation *TeamMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (tc *TeamCreate) SetName(s string) *TeamCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetDescription sets the "description" field.
func (tc *TeamCreate) SetDescription(s string) *TeamCreate {
	tc.mutation.SetDescription(s)
	return tc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tc *TeamCreate) SetNillableDescription(s *string) *TeamCreate {
	if s != nil {
		tc.SetDescription(*s)
	}
	return tc
}

// SetCtftimeID sets the "ctftime_id" field.
func (tc *TeamCreate) SetCtftimeID(i int) *TeamCreate {
	tc.mutation.SetCtftimeID(i)
	return tc
}

// SetNillableCtftimeID sets the "ctftime_id" field if the given value is not nil.
func (tc *TeamCreate) SetNillableCtftimeID(i *int) *TeamCreate {
	if i != nil {
		tc.SetCtftimeID(*i)
	}
	return tc
}

// SetCtftimeVerifiedAt sets the "ctftime_verified_at" field.
func (tc *TeamCreate) SetCtftimeVerifiedAt(t time.Time) *TeamCreate {
	tc.mutation.SetCtftimeVerifiedAt(t)
	return tc
}

// SetNillableCtftimeVerifiedAt sets the "ctftime_verified_at" field if the given value is not nil.
func (tc *TeamCreate) SetNillableCtftimeVerifiedAt(t *time.Time) *TeamCreate {
	if t != nil {
		tc.SetCtftimeVerifiedAt(*t)
	}
	return tc
}

// SetLogo sets the "logo" field.
func (tc *TeamCreate) SetLogo(b []byte) *TeamCreate {
	tc.mutation.SetLogo(b)
	return tc
}

// SetVerifiedAt sets the "verified_at" field.
func (tc *TeamCreate) SetVerifiedAt(t time.Time) *TeamCreate {
	tc.mutation.SetVerifiedAt(t)
	return tc
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (tc *TeamCreate) SetNillableVerifiedAt(t *time.Time) *TeamCreate {
	if t != nil {
		tc.SetVerifiedAt(*t)
	}
	return tc
}

// SetCaptainID sets the "captain" edge to the User entity by ID.
func (tc *TeamCreate) SetCaptainID(id int) *TeamCreate {
	tc.mutation.SetCaptainID(id)
	return tc
}

// SetNillableCaptainID sets the "captain" edge to the User entity by ID if the given value is not nil.
func (tc *TeamCreate) SetNillableCaptainID(id *int) *TeamCreate {
	if id != nil {
		tc = tc.SetCaptainID(*id)
	}
	return tc
}

// SetCaptain sets the "captain" edge to the User entity.
func (tc *TeamCreate) SetCaptain(u *User) *TeamCreate {
	return tc.SetCaptainID(u.ID)
}

// SetVerifiedByID sets the "verified_by" edge to the User entity by ID.
func (tc *TeamCreate) SetVerifiedByID(id int) *TeamCreate {
	tc.mutation.SetVerifiedByID(id)
	return tc
}

// SetNillableVerifiedByID sets the "verified_by" edge to the User entity by ID if the given value is not nil.
func (tc *TeamCreate) SetNillableVerifiedByID(id *int) *TeamCreate {
	if id != nil {
		tc = tc.SetVerifiedByID(*id)
	}
	return tc
}

// SetVerifiedBy sets the "verified_by" edge to the User entity.
func (tc *TeamCreate) SetVerifiedBy(u *User) *TeamCreate {
	return tc.SetVerifiedByID(u.ID)
}

// AddMemberIDs adds the "members" edge to the User entity by IDs.
func (tc *TeamCreate) AddMemberIDs(ids ...int) *TeamCreate {
	tc.mutation.AddMemberIDs(ids...)
	return tc
}

// AddMembers adds the "members" edges to the User entity.
func (tc *TeamCreate) AddMembers(u ...*User) *TeamCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return tc.AddMemberIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (tc *TeamCreate) Mutation() *TeamMutation {
	return tc.mutation
}

// Save creates the Team in the database.
func (tc *TeamCreate) Save(ctx context.Context) (*Team, error) {
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TeamCreate) SaveX(ctx context.Context) *Team {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TeamCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TeamCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TeamCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Team.name"`)}
	}
	if v, ok := tc.mutation.Logo(); ok {
		if err := team.LogoValidator(v); err != nil {
			return &ValidationError{Name: "logo", err: fmt.Errorf(`ent: validator failed for field "Team.logo": %w`, err)}
		}
	}
	return nil
}

func (tc *TeamCreate) sqlSave(ctx context.Context) (*Team, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TeamCreate) createSpec() (*Team, *sqlgraph.CreateSpec) {
	var (
		_node = &Team{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(team.Table, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt))
	)
	_spec.OnConflict = tc.conflict
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Description(); ok {
		_spec.SetField(team.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := tc.mutation.CtftimeID(); ok {
		_spec.SetField(team.FieldCtftimeID, field.TypeInt, value)
		_node.CtftimeID = &value
	}
	if value, ok := tc.mutation.CtftimeVerifiedAt(); ok {
		_spec.SetField(team.FieldCtftimeVerifiedAt, field.TypeTime, value)
		_node.CtftimeVerifiedAt = &value
	}
	if value, ok := tc.mutation.Logo(); ok {
		_spec.SetField(team.FieldLogo, field.TypeBytes, value)
		_node.Logo = value
	}
	if value, ok := tc.mutation.VerifiedAt(); ok {
		_spec.SetField(team.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if nodes := tc.mutation.CaptainIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.CaptainTable,
			Columns: []string{team.CaptainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.team_captain = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.VerifiedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.VerifiedByTable,
			Columns: []string{team.VerifiedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.team_verified_by = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: team.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Team.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (tc *TeamCreate) OnConflict(opts ...sql.ConflictOption) *TeamUpsertOne {
	tc.conflict = opts
	return &TeamUpsertOne{
		create: tc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tc *TeamCreate) OnConflictColumns(columns ...string) *TeamUpsertOne {
	tc.conflict = append(tc.conflict, sql.ConflictColumns(columns...))
	return &TeamUpsertOne{
		create: tc,
	}
}

type (
	// TeamUpsertOne is the builder for "upsert"-ing
	//  one Team node.
	TeamUpsertOne struct {
		create *TeamCreate
	}

	// TeamUpsert is the "OnConflict" setter.
	TeamUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *TeamUpsert) SetName(v string) *TeamUpsert {
	u.Set(team.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TeamUpsert) UpdateName() *TeamUpsert {
	u.SetExcluded(team.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *TeamUpsert) SetDescription(v string) *TeamUpsert {
	u.Set(team.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TeamUpsert) UpdateDescription() *TeamUpsert {
	u.SetExcluded(team.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *TeamUpsert) ClearDescription() *TeamUpsert {
	u.SetNull(team.FieldDescription)
	return u
}

// SetCtftimeID sets the "ctftime_id" field.
func (u *TeamUpsert) SetCtftimeID(v int) *TeamUpsert {
	u.Set(team.FieldCtftimeID, v)
	return u
}

// UpdateCtftimeID sets the "ctftime_id" field to the value that was provided on create.
func (u *TeamUpsert) UpdateCtftimeID() *TeamUpsert {
	u.SetExcluded(team.FieldCtftimeID)
	return u
}

// AddCtftimeID adds v to the "ctftime_id" field.
func (u *TeamUpsert) AddCtftimeID(v int) *TeamUpsert {
	u.Add(team.FieldCtftimeID, v)
	return u
}

// ClearCtftimeID clears the value of the "ctftime_id" field.
func (u *TeamUpsert) ClearCtftimeID() *TeamUpsert {
	u.SetNull(team.FieldCtftimeID)
	return u
}

// SetCtftimeVerifiedAt sets the "ctftime_verified_at" field.
func (u *TeamUpsert) SetCtftimeVerifiedAt(v time.Time) *TeamUpsert {
	u.Set(team.FieldCtftimeVerifiedAt, v)
	return u
}

// UpdateCtftimeVerifiedAt sets the "ctftime_verified_at" field to the value that was provided on create.
func (u *TeamUpsert) UpdateCtftimeVerifiedAt() *TeamUpsert {
	u.SetExcluded(team.FieldCtftimeVerifiedAt)
	return u
}

// ClearCtftimeVerifiedAt clears the value of the "ctftime_verified_at" field.
func (u *TeamUpsert) ClearCtftimeVerifiedAt() *TeamUpsert {
	u.SetNull(team.FieldCtftimeVerifiedAt)
	return u
}

// SetLogo sets the "logo" field.
func (u *TeamUpsert) SetLogo(v []byte) *TeamUpsert {
	u.Set(team.FieldLogo, v)
	return u
}

// UpdateLogo sets the "logo" field to the value that was provided on create.
func (u *TeamUpsert) UpdateLogo() *TeamUpsert {
	u.SetExcluded(team.FieldLogo)
	return u
}

// ClearLogo clears the value of the "logo" field.
func (u *TeamUpsert) ClearLogo() *TeamUpsert {
	u.SetNull(team.FieldLogo)
	return u
}

// SetVerifiedAt sets the "verified_at" field.
func (u *TeamUpsert) SetVerifiedAt(v time.Time) *TeamUpsert {
	u.Set(team.FieldVerifiedAt, v)
	return u
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *TeamUpsert) UpdateVerifiedAt() *TeamUpsert {
	u.SetExcluded(team.FieldVerifiedAt)
	return u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *TeamUpsert) ClearVerifiedAt() *TeamUpsert {
	u.SetNull(team.FieldVerifiedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamUpsertOne) UpdateNewValues() *TeamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Team.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamUpsertOne) Ignore() *TeamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamUpsertOne) DoNothing() *TeamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamCreate.OnConflict
// documentation for more info.
func (u *TeamUpsertOne) Update(set func(*TeamUpsert)) *TeamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TeamUpsertOne) SetName(v string) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateName() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *TeamUpsertOne) SetDescription(v string) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateDescription() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TeamUpsertOne) ClearDescription() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.ClearDescription()
	})
}

// SetCtftimeID sets the "ctftime_id" field.
func (u *TeamUpsertOne) SetCtftimeID(v int) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetCtftimeID(v)
	})
}

// AddCtftimeID adds v to the "ctftime_id" field.
func (u *TeamUpsertOne) AddCtftimeID(v int) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.AddCtftimeID(v)
	})
}

// UpdateCtftimeID sets the "ctftime_id" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateCtftimeID() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateCtftimeID()
	})
}

// ClearCtftimeID clears the value of the "ctftime_id" field.
func (u *TeamUpsertOne) ClearCtftimeID() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.ClearCtftimeID()
	})
}

// SetCtftimeVerifiedAt sets the "ctftime_verified_at" field.
func (u *TeamUpsertOne) SetCtftimeVerifiedAt(v time.Time) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetCtftimeVerifiedAt(v)
	})
}

// UpdateCtftimeVerifiedAt sets the "ctftime_verified_at" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateCtftimeVerifiedAt() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateCtftimeVerifiedAt()
	})
}

// ClearCtftimeVerifiedAt clears the value of the "ctftime_verified_at" field.
func (u *TeamUpsertOne) ClearCtftimeVerifiedAt() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.ClearCtftimeVerifiedAt()
	})
}

// SetLogo sets the "logo" field.
func (u *TeamUpsertOne) SetLogo(v []byte) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetLogo(v)
	})
}

// UpdateLogo sets the "logo" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateLogo() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateLogo()
	})
}

// ClearLogo clears the value of the "logo" field.
func (u *TeamUpsertOne) ClearLogo() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.ClearLogo()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *TeamUpsertOne) SetVerifiedAt(v time.Time) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateVerifiedAt() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *TeamUpsertOne) ClearVerifiedAt() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.ClearVerifiedAt()
	})
}

// Exec executes the query.
func (u *TeamUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamCreateBulk is the builder for creating many Team entities in bulk.
type TeamCreateBulk struct {
	config
	err      error
	builders []*TeamCreate
	conflict []sql.ConflictOption
}

// Save creates the Team entities in the database.
func (tcb *TeamCreateBulk) Save(ctx context.Context) ([]*Team, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Team, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TeamCreateBulk) SaveX(ctx context.Context) []*Team {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TeamCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TeamCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Team.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (tcb *TeamCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamUpsertBulk {
	tcb.conflict = opts
	return &TeamUpsertBulk{
		create: tcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tcb *TeamCreateBulk) OnConflictColumns(columns ...string) *TeamUpsertBulk {
	tcb.conflict = append(tcb.conflict, sql.ConflictColumns(columns...))
	return &TeamUpsertBulk{
		create: tcb,
	}
}

// TeamUpsertBulk is the builder for "upsert"-ing
// a bulk of Team nodes.
type TeamUpsertBulk struct {
	create *TeamCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamUpsertBulk) UpdateNewValues() *TeamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamUpsertBulk) Ignore() *TeamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamUpsertBulk) DoNothing() *TeamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamCreateBulk.OnConflict
// documentation for more info.
func (u *TeamUpsertBulk) Update(set func(*TeamUpsert)) *TeamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TeamUpsertBulk) SetName(v string) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateName() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *TeamUpsertBulk) SetDescription(v string) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateDescription() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TeamUpsertBulk) ClearDescription() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.ClearDescription()
	})
}

// SetCtftimeID sets the "ctftime_id" field.
func (u *TeamUpsertBulk) SetCtftimeID(v int) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetCtftimeID(v)
	})
}

// AddCtftimeID adds v to the "ctftime_id" field.
func (u *TeamUpsertBulk) AddCtftimeID(v int) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.AddCtftimeID(v)
	})
}

// UpdateCtftimeID sets the "ctftime_id" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateCtftimeID() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateCtftimeID()
	})
}

// ClearCtftimeID clears the value of the "ctftime_id" field.
func (u *TeamUpsertBulk) ClearCtftimeID() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.ClearCtftimeID()
	})
}

// SetCtftimeVerifiedAt sets the "ctftime_verified_at" field.
func (u *TeamUpsertBulk) SetCtftimeVerifiedAt(v time.Time) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetCtftimeVerifiedAt(v)
	})
}

// UpdateCtftimeVerifiedAt sets the "ctftime_verified_at" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateCtftimeVerifiedAt() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateCtftimeVerifiedAt()
	})
}

// ClearCtftimeVerifiedAt clears the value of the "ctftime_verified_at" field.
func (u *TeamUpsertBulk) ClearCtftimeVerifiedAt() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.ClearCtftimeVerifiedAt()
	})
}

// SetLogo sets the "logo" field.
func (u *TeamUpsertBulk) SetLogo(v []byte) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetLogo(v)
	})
}

// UpdateLogo sets the "logo" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateLogo() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateLogo()
	})
}

// ClearLogo clears the value of the "logo" field.
func (u *TeamUpsertBulk) ClearLogo() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.ClearLogo()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *TeamUpsertBulk) SetVerifiedAt(v time.Time) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateVerifiedAt() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *TeamUpsertBulk) ClearVerifiedAt() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.ClearVerifiedAt()
	})
}

// Exec executes the query.
func (u *TeamUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
