// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"openctfbackend/ent/user"
	"openctfbackend/ent/userprofile"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserProfile is the model entity for the UserProfile schema.
type UserProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Location holds the value of the "location" field.
	Location *string `json:"location"`
	// GithubLink holds the value of the "github_link" field.
	GithubLink *string `json:"github_link"`
	// LinkedinLink holds the value of the "linkedin_link" field.
	LinkedinLink *string `json:"linkedin_link"`
	// TwitterLink holds the value of the "twitter_link" field.
	TwitterLink *string `json:"twitter_link"`
	// WebsiteLink holds the value of the "website_link" field.
	WebsiteLink *string `json:"website_link"`
	// WebSkillLevel holds the value of the "web_skill_level" field.
	WebSkillLevel int `json:"web_skill_level"`
	// RevSkillLevel holds the value of the "rev_skill_level" field.
	RevSkillLevel int `json:"rev_skill_level"`
	// PwnSkillLevel holds the value of the "pwn_skill_level" field.
	PwnSkillLevel int `json:"pwn_skill_level"`
	// CryptoSkillLevel holds the value of the "crypto_skill_level" field.
	CryptoSkillLevel int `json:"crypto_skill_level"`
	// MiscSkillLevel holds the value of the "misc_skill_level" field.
	MiscSkillLevel int `json:"misc_skill_level"`
	// ShowEmail holds the value of the "show_email" field.
	ShowEmail bool `json:"show_email"`
	// ShowLocation holds the value of the "show_location" field.
	ShowLocation bool `json:"show_location"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserProfileQuery when eager-loading is set.
	Edges             UserProfileEdges `json:"edges"`
	user_profile_user *int
	selectValues      sql.SelectValues
}

// UserProfileEdges holds the relations/edges for other nodes in the graph.
type UserProfileEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserProfileEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userprofile.FieldShowEmail, userprofile.FieldShowLocation:
			values[i] = new(sql.NullBool)
		case userprofile.FieldID, userprofile.FieldWebSkillLevel, userprofile.FieldRevSkillLevel, userprofile.FieldPwnSkillLevel, userprofile.FieldCryptoSkillLevel, userprofile.FieldMiscSkillLevel:
			values[i] = new(sql.NullInt64)
		case userprofile.FieldLocation, userprofile.FieldGithubLink, userprofile.FieldLinkedinLink, userprofile.FieldTwitterLink, userprofile.FieldWebsiteLink:
			values[i] = new(sql.NullString)
		case userprofile.ForeignKeys[0]: // user_profile_user
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserProfile fields.
func (_m *UserProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userprofile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userprofile.FieldLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value.Valid {
				_m.Location = new(string)
				*_m.Location = value.String
			}
		case userprofile.FieldGithubLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field github_link", values[i])
			} else if value.Valid {
				_m.GithubLink = new(string)
				*_m.GithubLink = value.String
			}
		case userprofile.FieldLinkedinLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field linkedin_link", values[i])
			} else if value.Valid {
				_m.LinkedinLink = new(string)
				*_m.LinkedinLink = value.String
			}
		case userprofile.FieldTwitterLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field twitter_link", values[i])
			} else if value.Valid {
				_m.TwitterLink = new(string)
				*_m.TwitterLink = value.String
			}
		case userprofile.FieldWebsiteLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field website_link", values[i])
			} else if value.Valid {
				_m.WebsiteLink = new(string)
				*_m.WebsiteLink = value.String
			}
		case userprofile.FieldWebSkillLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field web_skill_level", values[i])
			} else if value.Valid {
				_m.WebSkillLevel = int(value.Int64)
			}
		case userprofile.FieldRevSkillLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rev_skill_level", values[i])
			} else if value.Valid {
				_m.RevSkillLevel = int(value.Int64)
			}
		case userprofile.FieldPwnSkillLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pwn_skill_level", values[i])
			} else if value.Valid {
				_m.PwnSkillLevel = int(value.Int64)
			}
		case userprofile.FieldCryptoSkillLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field crypto_skill_level", values[i])
			} else if value.Valid {
				_m.CryptoSkillLevel = int(value.Int64)
			}
		case userprofile.FieldMiscSkillLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field misc_skill_level", values[i])
			} else if value.Valid {
				_m.MiscSkillLevel = int(value.Int64)
			}
		case userprofile.FieldShowEmail:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field show_email", values[i])
			} else if value.Valid {
				_m.ShowEmail = value.Bool
			}
		case userprofile.FieldShowLocation:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field show_location", values[i])
			} else if value.Valid {
				_m.ShowLocation = value.Bool
			}
		case userprofile.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_profile_user", value)
			} else if value.Valid {
				_m.user_profile_user = new(int)
				*_m.user_profile_user = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserProfile.
// This includes values selected through modifiers, order, etc.
func (_m *UserProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserProfile entity.
func (_m *UserProfile) QueryUser() *UserQuery {
	return NewUserProfileClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserProfile.
// Note that you need to call UserProfile.Unwrap() before calling this method if this UserProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserProfile) Update() *UserProfileUpdateOne {
	return NewUserProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserProfile) Unwrap() *UserProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserProfile) String() string {
	var builder strings.Builder
	builder.WriteString("UserProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.Location; v != nil {
		builder.WriteString("location=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GithubLink; v != nil {
		builder.WriteString("github_link=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LinkedinLink; v != nil {
		builder.WriteString("linkedin_link=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TwitterLink; v != nil {
		builder.WriteString("twitter_link=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.WebsiteLink; v != nil {
		builder.WriteString("website_link=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("web_skill_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.WebSkillLevel))
	builder.WriteString(", ")
	builder.WriteString("rev_skill_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.RevSkillLevel))
	builder.WriteString(", ")
	builder.WriteString("pwn_skill_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.PwnSkillLevel))
	builder.WriteString(", ")
	builder.WriteString("crypto_skill_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.CryptoSkillLevel))
	builder.WriteString(", ")
	builder.WriteString("misc_skill_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.MiscSkillLevel))
	builder.WriteString(", ")
	builder.WriteString("show_email=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShowEmail))
	builder.WriteString(", ")
	builder.WriteString("show_location=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShowLocation))
	builder.WriteByte(')')
	return builder.String()
}

// UserProfiles is a parsable slice of UserProfile.
type UserProfiles []*UserProfile
