// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"openctfbackend/ent/predicate"
	"openctfbackend/ent/weightrating"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WeightRatingDelete is the builder for deleting a WeightRating entity.
type WeightRatingDelete struct {
	config
	hooks    []Hook
	mutation *WeightRatingMutation
}

// Where appends a list predicates to the WeightRatingDelete builder.
func (_d *WeightRatingDelete) Where(ps ...predicate.WeightRating) *WeightRatingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *WeightRatingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WeightRatingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *WeightRatingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(weightrating.Table, sqlgraph.NewFieldSpec(weightrating.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WeightRatingDeleteOne is the builder for deleting a single WeightRating entity.
type WeightRatingDeleteOne struct {
	_d *WeightRatingDelete
}

// Where appends a list predicates to the WeightRatingDelete builder.
func (_d *WeightRatingDeleteOne) Where(ps ...predicate.WeightRating) *WeightRatingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *WeightRatingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{weightrating.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WeightRatingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
