// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"openctfbackend/ent/contest"
	"openctfbackend/ent/team"
	"openctfbackend/ent/weightrating"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// WeightRating is the model entity for the WeightRating schema.
type WeightRating struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Difficulty holds the value of the "difficulty" field.
	Difficulty int `json:"difficulty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WeightRatingQuery when eager-loading is set.
	Edges                       WeightRatingEdges `json:"edges"`
	weight_rating_captains_team *int
	weight_rating_contest       *int
	selectValues                sql.SelectValues
}

// WeightRatingEdges holds the relations/edges for other nodes in the graph.
type WeightRatingEdges struct {
	// CaptainsTeam holds the value of the captains_team edge.
	CaptainsTeam *Team `json:"captains_team,omitempty"`
	// Contest holds the value of the contest edge.
	Contest *Contest `json:"contest,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CaptainsTeamOrErr returns the CaptainsTeam value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WeightRatingEdges) CaptainsTeamOrErr() (*Team, error) {
	if e.CaptainsTeam != nil {
		return e.CaptainsTeam, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "captains_team"}
}

// ContestOrErr returns the Contest value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WeightRatingEdges) ContestOrErr() (*Contest, error) {
	if e.Contest != nil {
		return e.Contest, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: contest.Label}
	}
	return nil, &NotLoadedError{edge: "contest"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WeightRating) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case weightrating.FieldID, weightrating.FieldDifficulty:
			values[i] = new(sql.NullInt64)
		case weightrating.ForeignKeys[0]: // weight_rating_captains_team
			values[i] = new(sql.NullInt64)
		case weightrating.ForeignKeys[1]: // weight_rating_contest
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WeightRating fields.
func (_m *WeightRating) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case weightrating.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case weightrating.FieldDifficulty:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field difficulty", values[i])
			} else if value.Valid {
				_m.Difficulty = int(value.Int64)
			}
		case weightrating.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field weight_rating_captains_team", value)
			} else if value.Valid {
				_m.weight_rating_captains_team = new(int)
				*_m.weight_rating_captains_team = int(value.Int64)
			}
		case weightrating.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field weight_rating_contest", value)
			} else if value.Valid {
				_m.weight_rating_contest = new(int)
				*_m.weight_rating_contest = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WeightRating.
// This includes values selected through modifiers, order, etc.
func (_m *WeightRating) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCaptainsTeam queries the "captains_team" edge of the WeightRating entity.
func (_m *WeightRating) QueryCaptainsTeam() *TeamQuery {
	return NewWeightRatingClient(_m.config).QueryCaptainsTeam(_m)
}

// QueryContest queries the "contest" edge of the WeightRating entity.
func (_m *WeightRating) QueryContest() *ContestQuery {
	return NewWeightRatingClient(_m.config).QueryContest(_m)
}

// Update returns a builder for updating this WeightRating.
// Note that you need to call WeightRating.Unwrap() before calling this method if this WeightRating
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WeightRating) Update() *WeightRatingUpdateOne {
	return NewWeightRatingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WeightRating entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WeightRating) Unwrap() *WeightRating {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WeightRating is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WeightRating) String() string {
	var builder strings.Builder
	builder.WriteString("WeightRating(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("difficulty=")
	builder.WriteString(fmt.Sprintf("%v", _m.Difficulty))
	builder.WriteByte(')')
	return builder.String()
}

// WeightRatings is a parsable slice of WeightRating.
type WeightRatings []*WeightRating
