// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"openctfbackend/ent/contest"
	"openctfbackend/ent/predicate"
	"openctfbackend/ent/team"
	"openctfbackend/ent/weightrating"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WeightRatingQuery is the builder for querying WeightRating entities.
type WeightRatingQuery struct {
	config
	ctx              *QueryContext
	order            []weightrating.OrderOption
	inters           []Interceptor
	predicates       []predicate.WeightRating
	withCaptainsTeam *TeamQuery
	withContest      *ContestQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WeightRatingQuery builder.
func (wrq *WeightRatingQuery) Where(ps ...predicate.WeightRating) *WeightRatingQuery {
	wrq.predicates = append(wrq.predicates, ps...)
	return wrq
}

// Limit the number of records to be returned by this query.
func (wrq *WeightRatingQuery) Limit(limit int) *WeightRatingQuery {
	wrq.ctx.Limit = &limit
	return wrq
}

// Offset to start from.
func (wrq *WeightRatingQuery) Offset(offset int) *WeightRatingQuery {
	wrq.ctx.Offset = &offset
	return wrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wrq *WeightRatingQuery) Unique(unique bool) *WeightRatingQuery {
	wrq.ctx.Unique = &unique
	return wrq
}

// Order specifies how the records should be ordered.
func (wrq *WeightRatingQuery) Order(o ...weightrating.OrderOption) *WeightRatingQuery {
	wrq.order = append(wrq.order, o...)
	return wrq
}

// QueryCaptainsTeam chains the current query on the "captains_team" edge.
func (wrq *WeightRatingQuery) QueryCaptainsTeam() *TeamQuery {
	query := (&TeamClient{config: wrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(weightrating.Table, weightrating.FieldID, selector),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, weightrating.CaptainsTeamTable, weightrating.CaptainsTeamColumn),
		)
		fromU = sqlgraph.SetNeighbors(wrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryContest chains the current query on the "contest" edge.
func (wrq *WeightRatingQuery) QueryContest() *ContestQuery {
	query := (&ContestClient{config: wrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(weightrating.Table, weightrating.FieldID, selector),
			sqlgraph.To(contest.Table, contest.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, weightrating.ContestTable, weightrating.ContestColumn),
		)
		fromU = sqlgraph.SetNeighbors(wrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WeightRating entity from the query.
// Returns a *NotFoundError when no WeightRating was found.
func (wrq *WeightRatingQuery) First(ctx context.Context) (*WeightRating, error) {
	nodes, err := wrq.Limit(1).All(setContextOp(ctx, wrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{weightrating.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wrq *WeightRatingQuery) FirstX(ctx context.Context) *WeightRating {
	node, err := wrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WeightRating ID from the query.
// Returns a *NotFoundError when no WeightRating ID was found.
func (wrq *WeightRatingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wrq.Limit(1).IDs(setContextOp(ctx, wrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{weightrating.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wrq *WeightRatingQuery) FirstIDX(ctx context.Context) int {
	id, err := wrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WeightRating entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WeightRating entity is found.
// Returns a *NotFoundError when no WeightRating entities are found.
func (wrq *WeightRatingQuery) Only(ctx context.Context) (*WeightRating, error) {
	nodes, err := wrq.Limit(2).All(setContextOp(ctx, wrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{weightrating.Label}
	default:
		return nil, &NotSingularError{weightrating.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wrq *WeightRatingQuery) OnlyX(ctx context.Context) *WeightRating {
	node, err := wrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WeightRating ID in the query.
// Returns a *NotSingularError when more than one WeightRating ID is found.
// Returns a *NotFoundError when no entities are found.
func (wrq *WeightRatingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wrq.Limit(2).IDs(setContextOp(ctx, wrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{weightrating.Label}
	default:
		err = &NotSingularError{weightrating.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wrq *WeightRatingQuery) OnlyIDX(ctx context.Context) int {
	id, err := wrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WeightRatings.
func (wrq *WeightRatingQuery) All(ctx context.Context) ([]*WeightRating, error) {
	ctx = setContextOp(ctx, wrq.ctx, ent.OpQueryAll)
	if err := wrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WeightRating, *WeightRatingQuery]()
	return withInterceptors[[]*WeightRating](ctx, wrq, qr, wrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wrq *WeightRatingQuery) AllX(ctx context.Context) []*WeightRating {
	nodes, err := wrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WeightRating IDs.
func (wrq *WeightRatingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wrq.ctx.Unique == nil && wrq.path != nil {
		wrq.Unique(true)
	}
	ctx = setContextOp(ctx, wrq.ctx, ent.OpQueryIDs)
	if err = wrq.Select(weightrating.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wrq *WeightRatingQuery) IDsX(ctx context.Context) []int {
	ids, err := wrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wrq *WeightRatingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wrq.ctx, ent.OpQueryCount)
	if err := wrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wrq, querierCount[*WeightRatingQuery](), wrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wrq *WeightRatingQuery) CountX(ctx context.Context) int {
	count, err := wrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wrq *WeightRatingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wrq.ctx, ent.OpQueryExist)
	switch _, err := wrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wrq *WeightRatingQuery) ExistX(ctx context.Context) bool {
	exist, err := wrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WeightRatingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wrq *WeightRatingQuery) Clone() *WeightRatingQuery {
	if wrq == nil {
		return nil
	}
	return &WeightRatingQuery{
		config:           wrq.config,
		ctx:              wrq.ctx.Clone(),
		order:            append([]weightrating.OrderOption{}, wrq.order...),
		inters:           append([]Interceptor{}, wrq.inters...),
		predicates:       append([]predicate.WeightRating{}, wrq.predicates...),
		withCaptainsTeam: wrq.withCaptainsTeam.Clone(),
		withContest:      wrq.withContest.Clone(),
		// clone intermediate query.
		sql:  wrq.sql.Clone(),
		path: wrq.path,
	}
}

// WithCaptainsTeam tells the query-builder to eager-load the nodes that are connected to
// the "captains_team" edge. The optional arguments are used to configure the query builder of the edge.
func (wrq *WeightRatingQuery) WithCaptainsTeam(opts ...func(*TeamQuery)) *WeightRatingQuery {
	query := (&TeamClient{config: wrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wrq.withCaptainsTeam = query
	return wrq
}

// WithContest tells the query-builder to eager-load the nodes that are connected to
// the "contest" edge. The optional arguments are used to configure the query builder of the edge.
func (wrq *WeightRatingQuery) WithContest(opts ...func(*ContestQuery)) *WeightRatingQuery {
	query := (&ContestClient{config: wrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wrq.withContest = query
	return wrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Difficulty int `json:"difficulty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WeightRating.Query().
//		GroupBy(weightrating.FieldDifficulty).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wrq *WeightRatingQuery) GroupBy(field string, fields ...string) *WeightRatingGroupBy {
	wrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WeightRatingGroupBy{build: wrq}
	grbuild.flds = &wrq.ctx.Fields
	grbuild.label = weightrating.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Difficulty int `json:"difficulty"`
//	}
//
//	client.WeightRating.Query().
//		Select(weightrating.FieldDifficulty).
//		Scan(ctx, &v)
func (wrq *WeightRatingQuery) Select(fields ...string) *WeightRatingSelect {
	wrq.ctx.Fields = append(wrq.ctx.Fields, fields...)
	sbuild := &WeightRatingSelect{WeightRatingQuery: wrq}
	sbuild.label = weightrating.Label
	sbuild.flds, sbuild.scan = &wrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WeightRatingSelect configured with the given aggregations.
func (wrq *WeightRatingQuery) Aggregate(fns ...AggregateFunc) *WeightRatingSelect {
	return wrq.Select().Aggregate(fns...)
}

func (wrq *WeightRatingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wrq); err != nil {
				return err
			}
		}
	}
	for _, f := range wrq.ctx.Fields {
		if !weightrating.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wrq.path != nil {
		prev, err := wrq.path(ctx)
		if err != nil {
			return err
		}
		wrq.sql = prev
	}
	return nil
}

func (wrq *WeightRatingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WeightRating, error) {
	var (
		nodes       = []*WeightRating{}
		withFKs     = wrq.withFKs
		_spec       = wrq.querySpec()
		loadedTypes = [2]bool{
			wrq.withCaptainsTeam != nil,
			wrq.withContest != nil,
		}
	)
	if wrq.withCaptainsTeam != nil || wrq.withContest != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, weightrating.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WeightRating).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WeightRating{config: wrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wrq.withCaptainsTeam; query != nil {
		if err := wrq.loadCaptainsTeam(ctx, query, nodes, nil,
			func(n *WeightRating, e *Team) { n.Edges.CaptainsTeam = e }); err != nil {
			return nil, err
		}
	}
	if query := wrq.withContest; query != nil {
		if err := wrq.loadContest(ctx, query, nodes, nil,
			func(n *WeightRating, e *Contest) { n.Edges.Contest = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wrq *WeightRatingQuery) loadCaptainsTeam(ctx context.Context, query *TeamQuery, nodes []*WeightRating, init func(*WeightRating), assign func(*WeightRating, *Team)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*WeightRating)
	for i := range nodes {
		if nodes[i].weight_rating_captains_team == nil {
			continue
		}
		fk := *nodes[i].weight_rating_captains_team
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(team.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "weight_rating_captains_team" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (wrq *WeightRatingQuery) loadContest(ctx context.Context, query *ContestQuery, nodes []*WeightRating, init func(*WeightRating), assign func(*WeightRating, *Contest)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*WeightRating)
	for i := range nodes {
		if nodes[i].weight_rating_contest == nil {
			continue
		}
		fk := *nodes[i].weight_rating_contest
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(contest.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "weight_rating_contest" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (wrq *WeightRatingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wrq.querySpec()
	_spec.Node.Columns = wrq.ctx.Fields
	if len(wrq.ctx.Fields) > 0 {
		_spec.Unique = wrq.ctx.Unique != nil && *wrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wrq.driver, _spec)
}

func (wrq *WeightRatingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(weightrating.Table, weightrating.Columns, sqlgraph.NewFieldSpec(weightrating.FieldID, field.TypeInt))
	_spec.From = wrq.sql
	if unique := wrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wrq.path != nil {
		_spec.Unique = true
	}
	if fields := wrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, weightrating.FieldID)
		for i := range fields {
			if fields[i] != weightrating.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wrq *WeightRatingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wrq.driver.Dialect())
	t1 := builder.Table(weightrating.Table)
	columns := wrq.ctx.Fields
	if len(columns) == 0 {
		columns = weightrating.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wrq.sql != nil {
		selector = wrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wrq.ctx.Unique != nil && *wrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wrq.predicates {
		p(selector)
	}
	for _, p := range wrq.order {
		p(selector)
	}
	if offset := wrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WeightRatingGroupBy is the group-by builder for WeightRating entities.
type WeightRatingGroupBy struct {
	selector
	build *WeightRatingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wrgb *WeightRatingGroupBy) Aggregate(fns ...AggregateFunc) *WeightRatingGroupBy {
	wrgb.fns = append(wrgb.fns, fns...)
	return wrgb
}

// Scan applies the selector query and scans the result into the given value.
func (wrgb *WeightRatingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wrgb.build.ctx, ent.OpQueryGroupBy)
	if err := wrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WeightRatingQuery, *WeightRatingGroupBy](ctx, wrgb.build, wrgb, wrgb.build.inters, v)
}

func (wrgb *WeightRatingGroupBy) sqlScan(ctx context.Context, root *WeightRatingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wrgb.fns))
	for _, fn := range wrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wrgb.flds)+len(wrgb.fns))
		for _, f := range *wrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WeightRatingSelect is the builder for selecting fields of WeightRating entities.
type WeightRatingSelect struct {
	*WeightRatingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wrs *WeightRatingSelect) Aggregate(fns ...AggregateFunc) *WeightRatingSelect {
	wrs.fns = append(wrs.fns, fns...)
	return wrs
}

// Scan applies the selector query and scans the result into the given value.
func (wrs *WeightRatingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wrs.ctx, ent.OpQuerySelect)
	if err := wrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WeightRatingQuery, *WeightRatingSelect](ctx, wrs.WeightRatingQuery, wrs, wrs.inters, v)
}

func (wrs *WeightRatingSelect) sqlScan(ctx context.Context, root *WeightRatingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wrs.fns))
	for _, fn := range wrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
