// Code generated by ent, DO NOT EDIT.

package aggregatedyearlyteam

import (
	"openctfbackend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID applies equality check predicate on the "id" field. It's identical to IDEQ.
func ID(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldDescription, v))
}

// CountryCode applies equality check predicate on the "country_code" field. It's identical to CountryCodeEQ.
func CountryCode(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldCountryCode, v))
}

// TeamLogoURL applies equality check predicate on the "team_logo_url" field. It's identical to TeamLogoURLEQ.
func TeamLogoURL(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldTeamLogoURL, v))
}

// BannerImageURL applies equality check predicate on the "banner_image_url" field. It's identical to BannerImageURLEQ.
func BannerImageURL(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldBannerImageURL, v))
}

// WebsiteURL applies equality check predicate on the "website_url" field. It's identical to WebsiteURLEQ.
func WebsiteURL(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldWebsiteURL, v))
}

// DiscordURL applies equality check predicate on the "discord_url" field. It's identical to DiscordURLEQ.
func DiscordURL(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldDiscordURL, v))
}

// GithubURL applies equality check predicate on the "github_url" field. It's identical to GithubURLEQ.
func GithubURL(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldGithubURL, v))
}

// Recruiting applies equality check predicate on the "recruiting" field. It's identical to RecruitingEQ.
func Recruiting(v bool) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldRecruiting, v))
}

// ContactInfo applies equality check predicate on the "contact_info" field. It's identical to ContactInfoEQ.
func ContactInfo(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldContactInfo, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldCreatedAt, v))
}

// CtftimeID applies equality check predicate on the "ctftime_id" field. It's identical to CtftimeIDEQ.
func CtftimeID(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldCtftimeID, v))
}

// CtftimeVerifiedAt applies equality check predicate on the "ctftime_verified_at" field. It's identical to CtftimeVerifiedAtEQ.
func CtftimeVerifiedAt(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldCtftimeVerifiedAt, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldVerifiedAt, v))
}

// Year applies equality check predicate on the "year" field. It's identical to YearEQ.
func Year(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldYear, v))
}

// Rank applies equality check predicate on the "rank" field. It's identical to RankEQ.
func Rank(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldRank, v))
}

// TeamPoints applies equality check predicate on the "team_points" field. It's identical to TeamPointsEQ.
func TeamPoints(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldTeamPoints, v))
}

// Members applies equality check predicate on the "members" field. It's identical to MembersEQ.
func Members(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldMembers, v))
}

// AvgPlace applies equality check predicate on the "avg_place" field. It's identical to AvgPlaceEQ.
func AvgPlace(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldAvgPlace, v))
}

// ContestsCount applies equality check predicate on the "contests_count" field. It's identical to ContestsCountEQ.
func ContestsCount(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldContestsCount, v))
}

// ContestsWon applies equality check predicate on the "contests_won" field. It's identical to ContestsWonEQ.
func ContestsWon(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldContestsWon, v))
}

// IDEQ applies the EQ predicate on the "id" field.
func IDEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldID, v))
}

// IDNEQ applies the NEQ predicate on the "id" field.
func IDNEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldID, v))
}

// IDIn applies the In predicate on the "id" field.
func IDIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldID, vs...))
}

// IDNotIn applies the NotIn predicate on the "id" field.
func IDNotIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldID, vs...))
}

// IDGT applies the GT predicate on the "id" field.
func IDGT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldID, v))
}

// IDGTE applies the GTE predicate on the "id" field.
func IDGTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldID, v))
}

// IDLT applies the LT predicate on the "id" field.
func IDLT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldID, v))
}

// IDLTE applies the LTE predicate on the "id" field.
func IDLTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContainsFold(FieldDescription, v))
}

// CountryCodeEQ applies the EQ predicate on the "country_code" field.
func CountryCodeEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldCountryCode, v))
}

// CountryCodeNEQ applies the NEQ predicate on the "country_code" field.
func CountryCodeNEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldCountryCode, v))
}

// CountryCodeIn applies the In predicate on the "country_code" field.
func CountryCodeIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldCountryCode, vs...))
}

// CountryCodeNotIn applies the NotIn predicate on the "country_code" field.
func CountryCodeNotIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldCountryCode, vs...))
}

// CountryCodeGT applies the GT predicate on the "country_code" field.
func CountryCodeGT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldCountryCode, v))
}

// CountryCodeGTE applies the GTE predicate on the "country_code" field.
func CountryCodeGTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldCountryCode, v))
}

// CountryCodeLT applies the LT predicate on the "country_code" field.
func CountryCodeLT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldCountryCode, v))
}

// CountryCodeLTE applies the LTE predicate on the "country_code" field.
func CountryCodeLTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldCountryCode, v))
}

// CountryCodeContains applies the Contains predicate on the "country_code" field.
func CountryCodeContains(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContains(FieldCountryCode, v))
}

// CountryCodeHasPrefix applies the HasPrefix predicate on the "country_code" field.
func CountryCodeHasPrefix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasPrefix(FieldCountryCode, v))
}

// CountryCodeHasSuffix applies the HasSuffix predicate on the "country_code" field.
func CountryCodeHasSuffix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasSuffix(FieldCountryCode, v))
}

// CountryCodeEqualFold applies the EqualFold predicate on the "country_code" field.
func CountryCodeEqualFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEqualFold(FieldCountryCode, v))
}

// CountryCodeContainsFold applies the ContainsFold predicate on the "country_code" field.
func CountryCodeContainsFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContainsFold(FieldCountryCode, v))
}

// TeamLogoURLEQ applies the EQ predicate on the "team_logo_url" field.
func TeamLogoURLEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldTeamLogoURL, v))
}

// TeamLogoURLNEQ applies the NEQ predicate on the "team_logo_url" field.
func TeamLogoURLNEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldTeamLogoURL, v))
}

// TeamLogoURLIn applies the In predicate on the "team_logo_url" field.
func TeamLogoURLIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldTeamLogoURL, vs...))
}

// TeamLogoURLNotIn applies the NotIn predicate on the "team_logo_url" field.
func TeamLogoURLNotIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldTeamLogoURL, vs...))
}

// TeamLogoURLGT applies the GT predicate on the "team_logo_url" field.
func TeamLogoURLGT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldTeamLogoURL, v))
}

// TeamLogoURLGTE applies the GTE predicate on the "team_logo_url" field.
func TeamLogoURLGTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldTeamLogoURL, v))
}

// TeamLogoURLLT applies the LT predicate on the "team_logo_url" field.
func TeamLogoURLLT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldTeamLogoURL, v))
}

// TeamLogoURLLTE applies the LTE predicate on the "team_logo_url" field.
func TeamLogoURLLTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldTeamLogoURL, v))
}

// TeamLogoURLContains applies the Contains predicate on the "team_logo_url" field.
func TeamLogoURLContains(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContains(FieldTeamLogoURL, v))
}

// TeamLogoURLHasPrefix applies the HasPrefix predicate on the "team_logo_url" field.
func TeamLogoURLHasPrefix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasPrefix(FieldTeamLogoURL, v))
}

// TeamLogoURLHasSuffix applies the HasSuffix predicate on the "team_logo_url" field.
func TeamLogoURLHasSuffix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasSuffix(FieldTeamLogoURL, v))
}

// TeamLogoURLIsNil applies the IsNil predicate on the "team_logo_url" field.
func TeamLogoURLIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldTeamLogoURL))
}

// TeamLogoURLNotNil applies the NotNil predicate on the "team_logo_url" field.
func TeamLogoURLNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldTeamLogoURL))
}

// TeamLogoURLEqualFold applies the EqualFold predicate on the "team_logo_url" field.
func TeamLogoURLEqualFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEqualFold(FieldTeamLogoURL, v))
}

// TeamLogoURLContainsFold applies the ContainsFold predicate on the "team_logo_url" field.
func TeamLogoURLContainsFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContainsFold(FieldTeamLogoURL, v))
}

// BannerImageURLEQ applies the EQ predicate on the "banner_image_url" field.
func BannerImageURLEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldBannerImageURL, v))
}

// BannerImageURLNEQ applies the NEQ predicate on the "banner_image_url" field.
func BannerImageURLNEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldBannerImageURL, v))
}

// BannerImageURLIn applies the In predicate on the "banner_image_url" field.
func BannerImageURLIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldBannerImageURL, vs...))
}

// BannerImageURLNotIn applies the NotIn predicate on the "banner_image_url" field.
func BannerImageURLNotIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldBannerImageURL, vs...))
}

// BannerImageURLGT applies the GT predicate on the "banner_image_url" field.
func BannerImageURLGT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldBannerImageURL, v))
}

// BannerImageURLGTE applies the GTE predicate on the "banner_image_url" field.
func BannerImageURLGTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldBannerImageURL, v))
}

// BannerImageURLLT applies the LT predicate on the "banner_image_url" field.
func BannerImageURLLT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldBannerImageURL, v))
}

// BannerImageURLLTE applies the LTE predicate on the "banner_image_url" field.
func BannerImageURLLTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldBannerImageURL, v))
}

// BannerImageURLContains applies the Contains predicate on the "banner_image_url" field.
func BannerImageURLContains(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContains(FieldBannerImageURL, v))
}

// BannerImageURLHasPrefix applies the HasPrefix predicate on the "banner_image_url" field.
func BannerImageURLHasPrefix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasPrefix(FieldBannerImageURL, v))
}

// BannerImageURLHasSuffix applies the HasSuffix predicate on the "banner_image_url" field.
func BannerImageURLHasSuffix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasSuffix(FieldBannerImageURL, v))
}

// BannerImageURLIsNil applies the IsNil predicate on the "banner_image_url" field.
func BannerImageURLIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldBannerImageURL))
}

// BannerImageURLNotNil applies the NotNil predicate on the "banner_image_url" field.
func BannerImageURLNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldBannerImageURL))
}

// BannerImageURLEqualFold applies the EqualFold predicate on the "banner_image_url" field.
func BannerImageURLEqualFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEqualFold(FieldBannerImageURL, v))
}

// BannerImageURLContainsFold applies the ContainsFold predicate on the "banner_image_url" field.
func BannerImageURLContainsFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContainsFold(FieldBannerImageURL, v))
}

// WebsiteURLEQ applies the EQ predicate on the "website_url" field.
func WebsiteURLEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldWebsiteURL, v))
}

// WebsiteURLNEQ applies the NEQ predicate on the "website_url" field.
func WebsiteURLNEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldWebsiteURL, v))
}

// WebsiteURLIn applies the In predicate on the "website_url" field.
func WebsiteURLIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldWebsiteURL, vs...))
}

// WebsiteURLNotIn applies the NotIn predicate on the "website_url" field.
func WebsiteURLNotIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldWebsiteURL, vs...))
}

// WebsiteURLGT applies the GT predicate on the "website_url" field.
func WebsiteURLGT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldWebsiteURL, v))
}

// WebsiteURLGTE applies the GTE predicate on the "website_url" field.
func WebsiteURLGTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldWebsiteURL, v))
}

// WebsiteURLLT applies the LT predicate on the "website_url" field.
func WebsiteURLLT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldWebsiteURL, v))
}

// WebsiteURLLTE applies the LTE predicate on the "website_url" field.
func WebsiteURLLTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldWebsiteURL, v))
}

// WebsiteURLContains applies the Contains predicate on the "website_url" field.
func WebsiteURLContains(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContains(FieldWebsiteURL, v))
}

// WebsiteURLHasPrefix applies the HasPrefix predicate on the "website_url" field.
func WebsiteURLHasPrefix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasPrefix(FieldWebsiteURL, v))
}

// WebsiteURLHasSuffix applies the HasSuffix predicate on the "website_url" field.
func WebsiteURLHasSuffix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasSuffix(FieldWebsiteURL, v))
}

// WebsiteURLIsNil applies the IsNil predicate on the "website_url" field.
func WebsiteURLIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldWebsiteURL))
}

// WebsiteURLNotNil applies the NotNil predicate on the "website_url" field.
func WebsiteURLNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldWebsiteURL))
}

// WebsiteURLEqualFold applies the EqualFold predicate on the "website_url" field.
func WebsiteURLEqualFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEqualFold(FieldWebsiteURL, v))
}

// WebsiteURLContainsFold applies the ContainsFold predicate on the "website_url" field.
func WebsiteURLContainsFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContainsFold(FieldWebsiteURL, v))
}

// DiscordURLEQ applies the EQ predicate on the "discord_url" field.
func DiscordURLEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldDiscordURL, v))
}

// DiscordURLNEQ applies the NEQ predicate on the "discord_url" field.
func DiscordURLNEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldDiscordURL, v))
}

// DiscordURLIn applies the In predicate on the "discord_url" field.
func DiscordURLIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldDiscordURL, vs...))
}

// DiscordURLNotIn applies the NotIn predicate on the "discord_url" field.
func DiscordURLNotIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldDiscordURL, vs...))
}

// DiscordURLGT applies the GT predicate on the "discord_url" field.
func DiscordURLGT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldDiscordURL, v))
}

// DiscordURLGTE applies the GTE predicate on the "discord_url" field.
func DiscordURLGTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldDiscordURL, v))
}

// DiscordURLLT applies the LT predicate on the "discord_url" field.
func DiscordURLLT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldDiscordURL, v))
}

// DiscordURLLTE applies the LTE predicate on the "discord_url" field.
func DiscordURLLTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldDiscordURL, v))
}

// DiscordURLContains applies the Contains predicate on the "discord_url" field.
func DiscordURLContains(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContains(FieldDiscordURL, v))
}

// DiscordURLHasPrefix applies the HasPrefix predicate on the "discord_url" field.
func DiscordURLHasPrefix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasPrefix(FieldDiscordURL, v))
}

// DiscordURLHasSuffix applies the HasSuffix predicate on the "discord_url" field.
func DiscordURLHasSuffix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasSuffix(FieldDiscordURL, v))
}

// DiscordURLIsNil applies the IsNil predicate on the "discord_url" field.
func DiscordURLIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldDiscordURL))
}

// DiscordURLNotNil applies the NotNil predicate on the "discord_url" field.
func DiscordURLNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldDiscordURL))
}

// DiscordURLEqualFold applies the EqualFold predicate on the "discord_url" field.
func DiscordURLEqualFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEqualFold(FieldDiscordURL, v))
}

// DiscordURLContainsFold applies the ContainsFold predicate on the "discord_url" field.
func DiscordURLContainsFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContainsFold(FieldDiscordURL, v))
}

// GithubURLEQ applies the EQ predicate on the "github_url" field.
func GithubURLEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldGithubURL, v))
}

// GithubURLNEQ applies the NEQ predicate on the "github_url" field.
func GithubURLNEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldGithubURL, v))
}

// GithubURLIn applies the In predicate on the "github_url" field.
func GithubURLIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldGithubURL, vs...))
}

// GithubURLNotIn applies the NotIn predicate on the "github_url" field.
func GithubURLNotIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldGithubURL, vs...))
}

// GithubURLGT applies the GT predicate on the "github_url" field.
func GithubURLGT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldGithubURL, v))
}

// GithubURLGTE applies the GTE predicate on the "github_url" field.
func GithubURLGTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldGithubURL, v))
}

// GithubURLLT applies the LT predicate on the "github_url" field.
func GithubURLLT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldGithubURL, v))
}

// GithubURLLTE applies the LTE predicate on the "github_url" field.
func GithubURLLTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldGithubURL, v))
}

// GithubURLContains applies the Contains predicate on the "github_url" field.
func GithubURLContains(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContains(FieldGithubURL, v))
}

// GithubURLHasPrefix applies the HasPrefix predicate on the "github_url" field.
func GithubURLHasPrefix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasPrefix(FieldGithubURL, v))
}

// GithubURLHasSuffix applies the HasSuffix predicate on the "github_url" field.
func GithubURLHasSuffix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasSuffix(FieldGithubURL, v))
}

// GithubURLIsNil applies the IsNil predicate on the "github_url" field.
func GithubURLIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldGithubURL))
}

// GithubURLNotNil applies the NotNil predicate on the "github_url" field.
func GithubURLNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldGithubURL))
}

// GithubURLEqualFold applies the EqualFold predicate on the "github_url" field.
func GithubURLEqualFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEqualFold(FieldGithubURL, v))
}

// GithubURLContainsFold applies the ContainsFold predicate on the "github_url" field.
func GithubURLContainsFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContainsFold(FieldGithubURL, v))
}

// RecruitingEQ applies the EQ predicate on the "recruiting" field.
func RecruitingEQ(v bool) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldRecruiting, v))
}

// RecruitingNEQ applies the NEQ predicate on the "recruiting" field.
func RecruitingNEQ(v bool) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldRecruiting, v))
}

// ContactInfoEQ applies the EQ predicate on the "contact_info" field.
func ContactInfoEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldContactInfo, v))
}

// ContactInfoNEQ applies the NEQ predicate on the "contact_info" field.
func ContactInfoNEQ(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldContactInfo, v))
}

// ContactInfoIn applies the In predicate on the "contact_info" field.
func ContactInfoIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldContactInfo, vs...))
}

// ContactInfoNotIn applies the NotIn predicate on the "contact_info" field.
func ContactInfoNotIn(vs ...string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldContactInfo, vs...))
}

// ContactInfoGT applies the GT predicate on the "contact_info" field.
func ContactInfoGT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldContactInfo, v))
}

// ContactInfoGTE applies the GTE predicate on the "contact_info" field.
func ContactInfoGTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldContactInfo, v))
}

// ContactInfoLT applies the LT predicate on the "contact_info" field.
func ContactInfoLT(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldContactInfo, v))
}

// ContactInfoLTE applies the LTE predicate on the "contact_info" field.
func ContactInfoLTE(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldContactInfo, v))
}

// ContactInfoContains applies the Contains predicate on the "contact_info" field.
func ContactInfoContains(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContains(FieldContactInfo, v))
}

// ContactInfoHasPrefix applies the HasPrefix predicate on the "contact_info" field.
func ContactInfoHasPrefix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasPrefix(FieldContactInfo, v))
}

// ContactInfoHasSuffix applies the HasSuffix predicate on the "contact_info" field.
func ContactInfoHasSuffix(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldHasSuffix(FieldContactInfo, v))
}

// ContactInfoIsNil applies the IsNil predicate on the "contact_info" field.
func ContactInfoIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldContactInfo))
}

// ContactInfoNotNil applies the NotNil predicate on the "contact_info" field.
func ContactInfoNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldContactInfo))
}

// ContactInfoEqualFold applies the EqualFold predicate on the "contact_info" field.
func ContactInfoEqualFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEqualFold(FieldContactInfo, v))
}

// ContactInfoContainsFold applies the ContainsFold predicate on the "contact_info" field.
func ContactInfoContainsFold(v string) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldContainsFold(FieldContactInfo, v))
}

// LookingForIsNil applies the IsNil predicate on the "looking_for" field.
func LookingForIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldLookingFor))
}

// LookingForNotNil applies the NotNil predicate on the "looking_for" field.
func LookingForNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldLookingFor))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldCreatedAt, v))
}

// CtftimeIDEQ applies the EQ predicate on the "ctftime_id" field.
func CtftimeIDEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldCtftimeID, v))
}

// CtftimeIDNEQ applies the NEQ predicate on the "ctftime_id" field.
func CtftimeIDNEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldCtftimeID, v))
}

// CtftimeIDIn applies the In predicate on the "ctftime_id" field.
func CtftimeIDIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldCtftimeID, vs...))
}

// CtftimeIDNotIn applies the NotIn predicate on the "ctftime_id" field.
func CtftimeIDNotIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldCtftimeID, vs...))
}

// CtftimeIDGT applies the GT predicate on the "ctftime_id" field.
func CtftimeIDGT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldCtftimeID, v))
}

// CtftimeIDGTE applies the GTE predicate on the "ctftime_id" field.
func CtftimeIDGTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldCtftimeID, v))
}

// CtftimeIDLT applies the LT predicate on the "ctftime_id" field.
func CtftimeIDLT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldCtftimeID, v))
}

// CtftimeIDLTE applies the LTE predicate on the "ctftime_id" field.
func CtftimeIDLTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldCtftimeID, v))
}

// CtftimeIDIsNil applies the IsNil predicate on the "ctftime_id" field.
func CtftimeIDIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldCtftimeID))
}

// CtftimeIDNotNil applies the NotNil predicate on the "ctftime_id" field.
func CtftimeIDNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldCtftimeID))
}

// CtftimeVerifiedAtEQ applies the EQ predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtEQ(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldCtftimeVerifiedAt, v))
}

// CtftimeVerifiedAtNEQ applies the NEQ predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtNEQ(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldCtftimeVerifiedAt, v))
}

// CtftimeVerifiedAtIn applies the In predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtIn(vs ...time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldCtftimeVerifiedAt, vs...))
}

// CtftimeVerifiedAtNotIn applies the NotIn predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtNotIn(vs ...time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldCtftimeVerifiedAt, vs...))
}

// CtftimeVerifiedAtGT applies the GT predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtGT(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldCtftimeVerifiedAt, v))
}

// CtftimeVerifiedAtGTE applies the GTE predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtGTE(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldCtftimeVerifiedAt, v))
}

// CtftimeVerifiedAtLT applies the LT predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtLT(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldCtftimeVerifiedAt, v))
}

// CtftimeVerifiedAtLTE applies the LTE predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtLTE(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldCtftimeVerifiedAt, v))
}

// CtftimeVerifiedAtIsNil applies the IsNil predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldCtftimeVerifiedAt))
}

// CtftimeVerifiedAtNotNil applies the NotNil predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldCtftimeVerifiedAt))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldVerifiedAt, v))
}

// VerifiedAtIsNil applies the IsNil predicate on the "verified_at" field.
func VerifiedAtIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldVerifiedAt))
}

// VerifiedAtNotNil applies the NotNil predicate on the "verified_at" field.
func VerifiedAtNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldVerifiedAt))
}

// YearEQ applies the EQ predicate on the "year" field.
func YearEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldYear, v))
}

// YearNEQ applies the NEQ predicate on the "year" field.
func YearNEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldYear, v))
}

// YearIn applies the In predicate on the "year" field.
func YearIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldYear, vs...))
}

// YearNotIn applies the NotIn predicate on the "year" field.
func YearNotIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldYear, vs...))
}

// YearGT applies the GT predicate on the "year" field.
func YearGT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldYear, v))
}

// YearGTE applies the GTE predicate on the "year" field.
func YearGTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldYear, v))
}

// YearLT applies the LT predicate on the "year" field.
func YearLT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldYear, v))
}

// YearLTE applies the LTE predicate on the "year" field.
func YearLTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldYear, v))
}

// RankEQ applies the EQ predicate on the "rank" field.
func RankEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldRank, v))
}

// RankNEQ applies the NEQ predicate on the "rank" field.
func RankNEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldRank, v))
}

// RankIn applies the In predicate on the "rank" field.
func RankIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldRank, vs...))
}

// RankNotIn applies the NotIn predicate on the "rank" field.
func RankNotIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldRank, vs...))
}

// RankGT applies the GT predicate on the "rank" field.
func RankGT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldRank, v))
}

// RankGTE applies the GTE predicate on the "rank" field.
func RankGTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldRank, v))
}

// RankLT applies the LT predicate on the "rank" field.
func RankLT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldRank, v))
}

// RankLTE applies the LTE predicate on the "rank" field.
func RankLTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldRank, v))
}

// TeamPointsEQ applies the EQ predicate on the "team_points" field.
func TeamPointsEQ(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldTeamPoints, v))
}

// TeamPointsNEQ applies the NEQ predicate on the "team_points" field.
func TeamPointsNEQ(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldTeamPoints, v))
}

// TeamPointsIn applies the In predicate on the "team_points" field.
func TeamPointsIn(vs ...float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldTeamPoints, vs...))
}

// TeamPointsNotIn applies the NotIn predicate on the "team_points" field.
func TeamPointsNotIn(vs ...float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldTeamPoints, vs...))
}

// TeamPointsGT applies the GT predicate on the "team_points" field.
func TeamPointsGT(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldTeamPoints, v))
}

// TeamPointsGTE applies the GTE predicate on the "team_points" field.
func TeamPointsGTE(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldTeamPoints, v))
}

// TeamPointsLT applies the LT predicate on the "team_points" field.
func TeamPointsLT(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldTeamPoints, v))
}

// TeamPointsLTE applies the LTE predicate on the "team_points" field.
func TeamPointsLTE(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldTeamPoints, v))
}

// TeamPointsIsNil applies the IsNil predicate on the "team_points" field.
func TeamPointsIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldTeamPoints))
}

// TeamPointsNotNil applies the NotNil predicate on the "team_points" field.
func TeamPointsNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldTeamPoints))
}

// MembersEQ applies the EQ predicate on the "members" field.
func MembersEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldMembers, v))
}

// MembersNEQ applies the NEQ predicate on the "members" field.
func MembersNEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldMembers, v))
}

// MembersIn applies the In predicate on the "members" field.
func MembersIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldMembers, vs...))
}

// MembersNotIn applies the NotIn predicate on the "members" field.
func MembersNotIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldMembers, vs...))
}

// MembersGT applies the GT predicate on the "members" field.
func MembersGT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldMembers, v))
}

// MembersGTE applies the GTE predicate on the "members" field.
func MembersGTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldMembers, v))
}

// MembersLT applies the LT predicate on the "members" field.
func MembersLT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldMembers, v))
}

// MembersLTE applies the LTE predicate on the "members" field.
func MembersLTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldMembers, v))
}

// MembersIsNil applies the IsNil predicate on the "members" field.
func MembersIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldMembers))
}

// MembersNotNil applies the NotNil predicate on the "members" field.
func MembersNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldMembers))
}

// AvgPlaceEQ applies the EQ predicate on the "avg_place" field.
func AvgPlaceEQ(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldAvgPlace, v))
}

// AvgPlaceNEQ applies the NEQ predicate on the "avg_place" field.
func AvgPlaceNEQ(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldAvgPlace, v))
}

// AvgPlaceIn applies the In predicate on the "avg_place" field.
func AvgPlaceIn(vs ...float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldAvgPlace, vs...))
}

// AvgPlaceNotIn applies the NotIn predicate on the "avg_place" field.
func AvgPlaceNotIn(vs ...float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldAvgPlace, vs...))
}

// AvgPlaceGT applies the GT predicate on the "avg_place" field.
func AvgPlaceGT(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldAvgPlace, v))
}

// AvgPlaceGTE applies the GTE predicate on the "avg_place" field.
func AvgPlaceGTE(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldAvgPlace, v))
}

// AvgPlaceLT applies the LT predicate on the "avg_place" field.
func AvgPlaceLT(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldAvgPlace, v))
}

// AvgPlaceLTE applies the LTE predicate on the "avg_place" field.
func AvgPlaceLTE(v float64) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldAvgPlace, v))
}

// AvgPlaceIsNil applies the IsNil predicate on the "avg_place" field.
func AvgPlaceIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldAvgPlace))
}

// AvgPlaceNotNil applies the NotNil predicate on the "avg_place" field.
func AvgPlaceNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldAvgPlace))
}

// ContestsCountEQ applies the EQ predicate on the "contests_count" field.
func ContestsCountEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldContestsCount, v))
}

// ContestsCountNEQ applies the NEQ predicate on the "contests_count" field.
func ContestsCountNEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldContestsCount, v))
}

// ContestsCountIn applies the In predicate on the "contests_count" field.
func ContestsCountIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldContestsCount, vs...))
}

// ContestsCountNotIn applies the NotIn predicate on the "contests_count" field.
func ContestsCountNotIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldContestsCount, vs...))
}

// ContestsCountGT applies the GT predicate on the "contests_count" field.
func ContestsCountGT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldContestsCount, v))
}

// ContestsCountGTE applies the GTE predicate on the "contests_count" field.
func ContestsCountGTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldContestsCount, v))
}

// ContestsCountLT applies the LT predicate on the "contests_count" field.
func ContestsCountLT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldContestsCount, v))
}

// ContestsCountLTE applies the LTE predicate on the "contests_count" field.
func ContestsCountLTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldContestsCount, v))
}

// ContestsCountIsNil applies the IsNil predicate on the "contests_count" field.
func ContestsCountIsNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIsNull(FieldContestsCount))
}

// ContestsCountNotNil applies the NotNil predicate on the "contests_count" field.
func ContestsCountNotNil() predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotNull(FieldContestsCount))
}

// ContestsWonEQ applies the EQ predicate on the "contests_won" field.
func ContestsWonEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldEQ(FieldContestsWon, v))
}

// ContestsWonNEQ applies the NEQ predicate on the "contests_won" field.
func ContestsWonNEQ(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNEQ(FieldContestsWon, v))
}

// ContestsWonIn applies the In predicate on the "contests_won" field.
func ContestsWonIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldIn(FieldContestsWon, vs...))
}

// ContestsWonNotIn applies the NotIn predicate on the "contests_won" field.
func ContestsWonNotIn(vs ...int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldNotIn(FieldContestsWon, vs...))
}

// ContestsWonGT applies the GT predicate on the "contests_won" field.
func ContestsWonGT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGT(FieldContestsWon, v))
}

// ContestsWonGTE applies the GTE predicate on the "contests_won" field.
func ContestsWonGTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldGTE(FieldContestsWon, v))
}

// ContestsWonLT applies the LT predicate on the "contests_won" field.
func ContestsWonLT(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLT(FieldContestsWon, v))
}

// ContestsWonLTE applies the LTE predicate on the "contests_won" field.
func ContestsWonLTE(v int) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.FieldLTE(FieldContestsWon, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AggregatedYearlyTeam) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AggregatedYearlyTeam) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AggregatedYearlyTeam) predicate.AggregatedYearlyTeam {
	return predicate.AggregatedYearlyTeam(sql.NotPredicates(p))
}
