// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Contest is the predicate function for contest builders.
type Contest func(*sql.Selector)

// ContestRating is the predicate function for contestrating builders.
type ContestRating func(*sql.Selector)

// Place is the predicate function for place builders.
type Place func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
