// Code generated by ent, DO NOT EDIT.

package aggregatedplatformstatistics

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the aggregatedplatformstatistics type in the database.
	Label = "aggregated_platform_statistics"
	// FieldTotalUsers holds the string denoting the total_users field in the database.
	FieldTotalUsers = "total_users"
	// FieldTotalTeams holds the string denoting the total_teams field in the database.
	FieldTotalTeams = "total_teams"
	// FieldTotalUpcomingEvents holds the string denoting the total_upcoming_events field in the database.
	FieldTotalUpcomingEvents = "total_upcoming_events"
	// FieldTotalPastEvents holds the string denoting the total_past_events field in the database.
	FieldTotalPastEvents = "total_past_events"
	// FieldTotalLiveEvents holds the string denoting the total_live_events field in the database.
	FieldTotalLiveEvents = "total_live_events"
	// Table holds the table name of the aggregatedplatformstatistics in the database.
	Table = "aggregated_platform_statistics"
)

// Columns holds all SQL columns for aggregatedplatformstatistics fields.
var Columns = []string{
	FieldTotalUsers,
	FieldTotalTeams,
	FieldTotalUpcomingEvents,
	FieldTotalPastEvents,
	FieldTotalLiveEvents,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the AggregatedPlatformStatistics queries.
type OrderOption func(*sql.Selector)

// ByTotalUsers orders the results by the total_users field.
func ByTotalUsers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalUsers, opts...).ToFunc()
}

// ByTotalTeams orders the results by the total_teams field.
func ByTotalTeams(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTeams, opts...).ToFunc()
}

// ByTotalUpcomingEvents orders the results by the total_upcoming_events field.
func ByTotalUpcomingEvents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalUpcomingEvents, opts...).ToFunc()
}

// ByTotalPastEvents orders the results by the total_past_events field.
func ByTotalPastEvents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPastEvents, opts...).ToFunc()
}

// ByTotalLiveEvents orders the results by the total_live_events field.
func ByTotalLiveEvents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalLiveEvents, opts...).ToFunc()
}
