// Code generated by ent, DO NOT EDIT.

package teamachievement

import (
	"openctfbackend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldEQ(FieldName, v))
}

// UnlockedAt applies equality check predicate on the "unlocked_at" field. It's identical to UnlockedAtEQ.
func UnlockedAt(v time.Time) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldEQ(FieldUnlockedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldContainsFold(FieldName, v))
}

// UnlockedAtEQ applies the EQ predicate on the "unlocked_at" field.
func UnlockedAtEQ(v time.Time) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldEQ(FieldUnlockedAt, v))
}

// UnlockedAtNEQ applies the NEQ predicate on the "unlocked_at" field.
func UnlockedAtNEQ(v time.Time) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldNEQ(FieldUnlockedAt, v))
}

// UnlockedAtIn applies the In predicate on the "unlocked_at" field.
func UnlockedAtIn(vs ...time.Time) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldIn(FieldUnlockedAt, vs...))
}

// UnlockedAtNotIn applies the NotIn predicate on the "unlocked_at" field.
func UnlockedAtNotIn(vs ...time.Time) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldNotIn(FieldUnlockedAt, vs...))
}

// UnlockedAtGT applies the GT predicate on the "unlocked_at" field.
func UnlockedAtGT(v time.Time) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldGT(FieldUnlockedAt, v))
}

// UnlockedAtGTE applies the GTE predicate on the "unlocked_at" field.
func UnlockedAtGTE(v time.Time) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldGTE(FieldUnlockedAt, v))
}

// UnlockedAtLT applies the LT predicate on the "unlocked_at" field.
func UnlockedAtLT(v time.Time) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldLT(FieldUnlockedAt, v))
}

// UnlockedAtLTE applies the LTE predicate on the "unlocked_at" field.
func UnlockedAtLTE(v time.Time) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.FieldLTE(FieldUnlockedAt, v))
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.TeamAchievement {
	return predicate.TeamAchievement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.TeamAchievement {
	return predicate.TeamAchievement(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamAchievement) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamAchievement) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamAchievement) predicate.TeamAchievement {
	return predicate.TeamAchievement(sql.NotPredicates(p))
}
