// Code generated by ent, DO NOT EDIT.

package aggregatedteamdetails

import (
	"openctfbackend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID applies equality check predicate on the "id" field. It's identical to IDEQ.
func ID(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldDescription, v))
}

// CtftimeID applies equality check predicate on the "ctftime_id" field. It's identical to CtftimeIDEQ.
func CtftimeID(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldCtftimeID, v))
}

// CtftimeVerifiedAt applies equality check predicate on the "ctftime_verified_at" field. It's identical to CtftimeVerifiedAtEQ.
func CtftimeVerifiedAt(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldCtftimeVerifiedAt, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldVerifiedAt, v))
}

// CountryCode applies equality check predicate on the "country_code" field. It's identical to CountryCodeEQ.
func CountryCode(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldCountryCode, v))
}

// TeamLogoURL applies equality check predicate on the "team_logo_url" field. It's identical to TeamLogoURLEQ.
func TeamLogoURL(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldTeamLogoURL, v))
}

// BannerImageURL applies equality check predicate on the "banner_image_url" field. It's identical to BannerImageURLEQ.
func BannerImageURL(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldBannerImageURL, v))
}

// DiscordURL applies equality check predicate on the "discord_url" field. It's identical to DiscordURLEQ.
func DiscordURL(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldDiscordURL, v))
}

// GithubURL applies equality check predicate on the "github_url" field. It's identical to GithubURLEQ.
func GithubURL(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldGithubURL, v))
}

// Recruiting applies equality check predicate on the "recruiting" field. It's identical to RecruitingEQ.
func Recruiting(v bool) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldRecruiting, v))
}

// ContactInfo applies equality check predicate on the "contact_info" field. It's identical to ContactInfoEQ.
func ContactInfo(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldContactInfo, v))
}

// WebsiteURL applies equality check predicate on the "website_url" field. It's identical to WebsiteURLEQ.
func WebsiteURL(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldWebsiteURL, v))
}

// CurrentPlace applies equality check predicate on the "current_place" field. It's identical to CurrentPlaceEQ.
func CurrentPlace(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldCurrentPlace, v))
}

// Points applies equality check predicate on the "points" field. It's identical to PointsEQ.
func Points(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldPoints, v))
}

// AvgPlace applies equality check predicate on the "avg_place" field. It's identical to AvgPlaceEQ.
func AvgPlace(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldAvgPlace, v))
}

// YearsActive applies equality check predicate on the "years_active" field. It's identical to YearsActiveEQ.
func YearsActive(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldYearsActive, v))
}

// IDEQ applies the EQ predicate on the "id" field.
func IDEQ(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldID, v))
}

// IDNEQ applies the NEQ predicate on the "id" field.
func IDNEQ(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldID, v))
}

// IDIn applies the In predicate on the "id" field.
func IDIn(vs ...int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldID, vs...))
}

// IDNotIn applies the NotIn predicate on the "id" field.
func IDNotIn(vs ...int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldID, vs...))
}

// IDGT applies the GT predicate on the "id" field.
func IDGT(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldID, v))
}

// IDGTE applies the GTE predicate on the "id" field.
func IDGTE(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldID, v))
}

// IDLT applies the LT predicate on the "id" field.
func IDLT(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldID, v))
}

// IDLTE applies the LTE predicate on the "id" field.
func IDLTE(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContainsFold(FieldDescription, v))
}

// CtftimeIDEQ applies the EQ predicate on the "ctftime_id" field.
func CtftimeIDEQ(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldCtftimeID, v))
}

// CtftimeIDNEQ applies the NEQ predicate on the "ctftime_id" field.
func CtftimeIDNEQ(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldCtftimeID, v))
}

// CtftimeIDIn applies the In predicate on the "ctftime_id" field.
func CtftimeIDIn(vs ...int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldCtftimeID, vs...))
}

// CtftimeIDNotIn applies the NotIn predicate on the "ctftime_id" field.
func CtftimeIDNotIn(vs ...int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldCtftimeID, vs...))
}

// CtftimeIDGT applies the GT predicate on the "ctftime_id" field.
func CtftimeIDGT(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldCtftimeID, v))
}

// CtftimeIDGTE applies the GTE predicate on the "ctftime_id" field.
func CtftimeIDGTE(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldCtftimeID, v))
}

// CtftimeIDLT applies the LT predicate on the "ctftime_id" field.
func CtftimeIDLT(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldCtftimeID, v))
}

// CtftimeIDLTE applies the LTE predicate on the "ctftime_id" field.
func CtftimeIDLTE(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldCtftimeID, v))
}

// CtftimeIDIsNil applies the IsNil predicate on the "ctftime_id" field.
func CtftimeIDIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldCtftimeID))
}

// CtftimeIDNotNil applies the NotNil predicate on the "ctftime_id" field.
func CtftimeIDNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldCtftimeID))
}

// CtftimeVerifiedAtEQ applies the EQ predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtEQ(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldCtftimeVerifiedAt, v))
}

// CtftimeVerifiedAtNEQ applies the NEQ predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtNEQ(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldCtftimeVerifiedAt, v))
}

// CtftimeVerifiedAtIn applies the In predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtIn(vs ...time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldCtftimeVerifiedAt, vs...))
}

// CtftimeVerifiedAtNotIn applies the NotIn predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtNotIn(vs ...time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldCtftimeVerifiedAt, vs...))
}

// CtftimeVerifiedAtGT applies the GT predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtGT(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldCtftimeVerifiedAt, v))
}

// CtftimeVerifiedAtGTE applies the GTE predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtGTE(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldCtftimeVerifiedAt, v))
}

// CtftimeVerifiedAtLT applies the LT predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtLT(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldCtftimeVerifiedAt, v))
}

// CtftimeVerifiedAtLTE applies the LTE predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtLTE(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldCtftimeVerifiedAt, v))
}

// CtftimeVerifiedAtIsNil applies the IsNil predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldCtftimeVerifiedAt))
}

// CtftimeVerifiedAtNotNil applies the NotNil predicate on the "ctftime_verified_at" field.
func CtftimeVerifiedAtNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldCtftimeVerifiedAt))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldVerifiedAt, v))
}

// VerifiedAtIsNil applies the IsNil predicate on the "verified_at" field.
func VerifiedAtIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldVerifiedAt))
}

// VerifiedAtNotNil applies the NotNil predicate on the "verified_at" field.
func VerifiedAtNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldVerifiedAt))
}

// CountryCodeEQ applies the EQ predicate on the "country_code" field.
func CountryCodeEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldCountryCode, v))
}

// CountryCodeNEQ applies the NEQ predicate on the "country_code" field.
func CountryCodeNEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldCountryCode, v))
}

// CountryCodeIn applies the In predicate on the "country_code" field.
func CountryCodeIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldCountryCode, vs...))
}

// CountryCodeNotIn applies the NotIn predicate on the "country_code" field.
func CountryCodeNotIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldCountryCode, vs...))
}

// CountryCodeGT applies the GT predicate on the "country_code" field.
func CountryCodeGT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldCountryCode, v))
}

// CountryCodeGTE applies the GTE predicate on the "country_code" field.
func CountryCodeGTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldCountryCode, v))
}

// CountryCodeLT applies the LT predicate on the "country_code" field.
func CountryCodeLT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldCountryCode, v))
}

// CountryCodeLTE applies the LTE predicate on the "country_code" field.
func CountryCodeLTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldCountryCode, v))
}

// CountryCodeContains applies the Contains predicate on the "country_code" field.
func CountryCodeContains(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContains(FieldCountryCode, v))
}

// CountryCodeHasPrefix applies the HasPrefix predicate on the "country_code" field.
func CountryCodeHasPrefix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasPrefix(FieldCountryCode, v))
}

// CountryCodeHasSuffix applies the HasSuffix predicate on the "country_code" field.
func CountryCodeHasSuffix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasSuffix(FieldCountryCode, v))
}

// CountryCodeEqualFold applies the EqualFold predicate on the "country_code" field.
func CountryCodeEqualFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEqualFold(FieldCountryCode, v))
}

// CountryCodeContainsFold applies the ContainsFold predicate on the "country_code" field.
func CountryCodeContainsFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContainsFold(FieldCountryCode, v))
}

// TeamLogoURLEQ applies the EQ predicate on the "team_logo_url" field.
func TeamLogoURLEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldTeamLogoURL, v))
}

// TeamLogoURLNEQ applies the NEQ predicate on the "team_logo_url" field.
func TeamLogoURLNEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldTeamLogoURL, v))
}

// TeamLogoURLIn applies the In predicate on the "team_logo_url" field.
func TeamLogoURLIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldTeamLogoURL, vs...))
}

// TeamLogoURLNotIn applies the NotIn predicate on the "team_logo_url" field.
func TeamLogoURLNotIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldTeamLogoURL, vs...))
}

// TeamLogoURLGT applies the GT predicate on the "team_logo_url" field.
func TeamLogoURLGT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldTeamLogoURL, v))
}

// TeamLogoURLGTE applies the GTE predicate on the "team_logo_url" field.
func TeamLogoURLGTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldTeamLogoURL, v))
}

// TeamLogoURLLT applies the LT predicate on the "team_logo_url" field.
func TeamLogoURLLT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldTeamLogoURL, v))
}

// TeamLogoURLLTE applies the LTE predicate on the "team_logo_url" field.
func TeamLogoURLLTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldTeamLogoURL, v))
}

// TeamLogoURLContains applies the Contains predicate on the "team_logo_url" field.
func TeamLogoURLContains(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContains(FieldTeamLogoURL, v))
}

// TeamLogoURLHasPrefix applies the HasPrefix predicate on the "team_logo_url" field.
func TeamLogoURLHasPrefix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasPrefix(FieldTeamLogoURL, v))
}

// TeamLogoURLHasSuffix applies the HasSuffix predicate on the "team_logo_url" field.
func TeamLogoURLHasSuffix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasSuffix(FieldTeamLogoURL, v))
}

// TeamLogoURLIsNil applies the IsNil predicate on the "team_logo_url" field.
func TeamLogoURLIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldTeamLogoURL))
}

// TeamLogoURLNotNil applies the NotNil predicate on the "team_logo_url" field.
func TeamLogoURLNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldTeamLogoURL))
}

// TeamLogoURLEqualFold applies the EqualFold predicate on the "team_logo_url" field.
func TeamLogoURLEqualFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEqualFold(FieldTeamLogoURL, v))
}

// TeamLogoURLContainsFold applies the ContainsFold predicate on the "team_logo_url" field.
func TeamLogoURLContainsFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContainsFold(FieldTeamLogoURL, v))
}

// BannerImageURLEQ applies the EQ predicate on the "banner_image_url" field.
func BannerImageURLEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldBannerImageURL, v))
}

// BannerImageURLNEQ applies the NEQ predicate on the "banner_image_url" field.
func BannerImageURLNEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldBannerImageURL, v))
}

// BannerImageURLIn applies the In predicate on the "banner_image_url" field.
func BannerImageURLIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldBannerImageURL, vs...))
}

// BannerImageURLNotIn applies the NotIn predicate on the "banner_image_url" field.
func BannerImageURLNotIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldBannerImageURL, vs...))
}

// BannerImageURLGT applies the GT predicate on the "banner_image_url" field.
func BannerImageURLGT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldBannerImageURL, v))
}

// BannerImageURLGTE applies the GTE predicate on the "banner_image_url" field.
func BannerImageURLGTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldBannerImageURL, v))
}

// BannerImageURLLT applies the LT predicate on the "banner_image_url" field.
func BannerImageURLLT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldBannerImageURL, v))
}

// BannerImageURLLTE applies the LTE predicate on the "banner_image_url" field.
func BannerImageURLLTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldBannerImageURL, v))
}

// BannerImageURLContains applies the Contains predicate on the "banner_image_url" field.
func BannerImageURLContains(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContains(FieldBannerImageURL, v))
}

// BannerImageURLHasPrefix applies the HasPrefix predicate on the "banner_image_url" field.
func BannerImageURLHasPrefix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasPrefix(FieldBannerImageURL, v))
}

// BannerImageURLHasSuffix applies the HasSuffix predicate on the "banner_image_url" field.
func BannerImageURLHasSuffix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasSuffix(FieldBannerImageURL, v))
}

// BannerImageURLIsNil applies the IsNil predicate on the "banner_image_url" field.
func BannerImageURLIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldBannerImageURL))
}

// BannerImageURLNotNil applies the NotNil predicate on the "banner_image_url" field.
func BannerImageURLNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldBannerImageURL))
}

// BannerImageURLEqualFold applies the EqualFold predicate on the "banner_image_url" field.
func BannerImageURLEqualFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEqualFold(FieldBannerImageURL, v))
}

// BannerImageURLContainsFold applies the ContainsFold predicate on the "banner_image_url" field.
func BannerImageURLContainsFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContainsFold(FieldBannerImageURL, v))
}

// DiscordURLEQ applies the EQ predicate on the "discord_url" field.
func DiscordURLEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldDiscordURL, v))
}

// DiscordURLNEQ applies the NEQ predicate on the "discord_url" field.
func DiscordURLNEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldDiscordURL, v))
}

// DiscordURLIn applies the In predicate on the "discord_url" field.
func DiscordURLIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldDiscordURL, vs...))
}

// DiscordURLNotIn applies the NotIn predicate on the "discord_url" field.
func DiscordURLNotIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldDiscordURL, vs...))
}

// DiscordURLGT applies the GT predicate on the "discord_url" field.
func DiscordURLGT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldDiscordURL, v))
}

// DiscordURLGTE applies the GTE predicate on the "discord_url" field.
func DiscordURLGTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldDiscordURL, v))
}

// DiscordURLLT applies the LT predicate on the "discord_url" field.
func DiscordURLLT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldDiscordURL, v))
}

// DiscordURLLTE applies the LTE predicate on the "discord_url" field.
func DiscordURLLTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldDiscordURL, v))
}

// DiscordURLContains applies the Contains predicate on the "discord_url" field.
func DiscordURLContains(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContains(FieldDiscordURL, v))
}

// DiscordURLHasPrefix applies the HasPrefix predicate on the "discord_url" field.
func DiscordURLHasPrefix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasPrefix(FieldDiscordURL, v))
}

// DiscordURLHasSuffix applies the HasSuffix predicate on the "discord_url" field.
func DiscordURLHasSuffix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasSuffix(FieldDiscordURL, v))
}

// DiscordURLIsNil applies the IsNil predicate on the "discord_url" field.
func DiscordURLIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldDiscordURL))
}

// DiscordURLNotNil applies the NotNil predicate on the "discord_url" field.
func DiscordURLNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldDiscordURL))
}

// DiscordURLEqualFold applies the EqualFold predicate on the "discord_url" field.
func DiscordURLEqualFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEqualFold(FieldDiscordURL, v))
}

// DiscordURLContainsFold applies the ContainsFold predicate on the "discord_url" field.
func DiscordURLContainsFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContainsFold(FieldDiscordURL, v))
}

// GithubURLEQ applies the EQ predicate on the "github_url" field.
func GithubURLEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldGithubURL, v))
}

// GithubURLNEQ applies the NEQ predicate on the "github_url" field.
func GithubURLNEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldGithubURL, v))
}

// GithubURLIn applies the In predicate on the "github_url" field.
func GithubURLIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldGithubURL, vs...))
}

// GithubURLNotIn applies the NotIn predicate on the "github_url" field.
func GithubURLNotIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldGithubURL, vs...))
}

// GithubURLGT applies the GT predicate on the "github_url" field.
func GithubURLGT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldGithubURL, v))
}

// GithubURLGTE applies the GTE predicate on the "github_url" field.
func GithubURLGTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldGithubURL, v))
}

// GithubURLLT applies the LT predicate on the "github_url" field.
func GithubURLLT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldGithubURL, v))
}

// GithubURLLTE applies the LTE predicate on the "github_url" field.
func GithubURLLTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldGithubURL, v))
}

// GithubURLContains applies the Contains predicate on the "github_url" field.
func GithubURLContains(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContains(FieldGithubURL, v))
}

// GithubURLHasPrefix applies the HasPrefix predicate on the "github_url" field.
func GithubURLHasPrefix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasPrefix(FieldGithubURL, v))
}

// GithubURLHasSuffix applies the HasSuffix predicate on the "github_url" field.
func GithubURLHasSuffix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasSuffix(FieldGithubURL, v))
}

// GithubURLIsNil applies the IsNil predicate on the "github_url" field.
func GithubURLIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldGithubURL))
}

// GithubURLNotNil applies the NotNil predicate on the "github_url" field.
func GithubURLNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldGithubURL))
}

// GithubURLEqualFold applies the EqualFold predicate on the "github_url" field.
func GithubURLEqualFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEqualFold(FieldGithubURL, v))
}

// GithubURLContainsFold applies the ContainsFold predicate on the "github_url" field.
func GithubURLContainsFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContainsFold(FieldGithubURL, v))
}

// RecruitingEQ applies the EQ predicate on the "recruiting" field.
func RecruitingEQ(v bool) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldRecruiting, v))
}

// RecruitingNEQ applies the NEQ predicate on the "recruiting" field.
func RecruitingNEQ(v bool) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldRecruiting, v))
}

// ContactInfoEQ applies the EQ predicate on the "contact_info" field.
func ContactInfoEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldContactInfo, v))
}

// ContactInfoNEQ applies the NEQ predicate on the "contact_info" field.
func ContactInfoNEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldContactInfo, v))
}

// ContactInfoIn applies the In predicate on the "contact_info" field.
func ContactInfoIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldContactInfo, vs...))
}

// ContactInfoNotIn applies the NotIn predicate on the "contact_info" field.
func ContactInfoNotIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldContactInfo, vs...))
}

// ContactInfoGT applies the GT predicate on the "contact_info" field.
func ContactInfoGT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldContactInfo, v))
}

// ContactInfoGTE applies the GTE predicate on the "contact_info" field.
func ContactInfoGTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldContactInfo, v))
}

// ContactInfoLT applies the LT predicate on the "contact_info" field.
func ContactInfoLT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldContactInfo, v))
}

// ContactInfoLTE applies the LTE predicate on the "contact_info" field.
func ContactInfoLTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldContactInfo, v))
}

// ContactInfoContains applies the Contains predicate on the "contact_info" field.
func ContactInfoContains(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContains(FieldContactInfo, v))
}

// ContactInfoHasPrefix applies the HasPrefix predicate on the "contact_info" field.
func ContactInfoHasPrefix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasPrefix(FieldContactInfo, v))
}

// ContactInfoHasSuffix applies the HasSuffix predicate on the "contact_info" field.
func ContactInfoHasSuffix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasSuffix(FieldContactInfo, v))
}

// ContactInfoIsNil applies the IsNil predicate on the "contact_info" field.
func ContactInfoIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldContactInfo))
}

// ContactInfoNotNil applies the NotNil predicate on the "contact_info" field.
func ContactInfoNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldContactInfo))
}

// ContactInfoEqualFold applies the EqualFold predicate on the "contact_info" field.
func ContactInfoEqualFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEqualFold(FieldContactInfo, v))
}

// ContactInfoContainsFold applies the ContainsFold predicate on the "contact_info" field.
func ContactInfoContainsFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContainsFold(FieldContactInfo, v))
}

// LookingForIsNil applies the IsNil predicate on the "looking_for" field.
func LookingForIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldLookingFor))
}

// LookingForNotNil applies the NotNil predicate on the "looking_for" field.
func LookingForNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldLookingFor))
}

// WebsiteURLEQ applies the EQ predicate on the "website_url" field.
func WebsiteURLEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldWebsiteURL, v))
}

// WebsiteURLNEQ applies the NEQ predicate on the "website_url" field.
func WebsiteURLNEQ(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldWebsiteURL, v))
}

// WebsiteURLIn applies the In predicate on the "website_url" field.
func WebsiteURLIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldWebsiteURL, vs...))
}

// WebsiteURLNotIn applies the NotIn predicate on the "website_url" field.
func WebsiteURLNotIn(vs ...string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldWebsiteURL, vs...))
}

// WebsiteURLGT applies the GT predicate on the "website_url" field.
func WebsiteURLGT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldWebsiteURL, v))
}

// WebsiteURLGTE applies the GTE predicate on the "website_url" field.
func WebsiteURLGTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldWebsiteURL, v))
}

// WebsiteURLLT applies the LT predicate on the "website_url" field.
func WebsiteURLLT(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldWebsiteURL, v))
}

// WebsiteURLLTE applies the LTE predicate on the "website_url" field.
func WebsiteURLLTE(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldWebsiteURL, v))
}

// WebsiteURLContains applies the Contains predicate on the "website_url" field.
func WebsiteURLContains(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContains(FieldWebsiteURL, v))
}

// WebsiteURLHasPrefix applies the HasPrefix predicate on the "website_url" field.
func WebsiteURLHasPrefix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasPrefix(FieldWebsiteURL, v))
}

// WebsiteURLHasSuffix applies the HasSuffix predicate on the "website_url" field.
func WebsiteURLHasSuffix(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldHasSuffix(FieldWebsiteURL, v))
}

// WebsiteURLIsNil applies the IsNil predicate on the "website_url" field.
func WebsiteURLIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldWebsiteURL))
}

// WebsiteURLNotNil applies the NotNil predicate on the "website_url" field.
func WebsiteURLNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldWebsiteURL))
}

// WebsiteURLEqualFold applies the EqualFold predicate on the "website_url" field.
func WebsiteURLEqualFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEqualFold(FieldWebsiteURL, v))
}

// WebsiteURLContainsFold applies the ContainsFold predicate on the "website_url" field.
func WebsiteURLContainsFold(v string) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldContainsFold(FieldWebsiteURL, v))
}

// CurrentPlaceEQ applies the EQ predicate on the "current_place" field.
func CurrentPlaceEQ(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldCurrentPlace, v))
}

// CurrentPlaceNEQ applies the NEQ predicate on the "current_place" field.
func CurrentPlaceNEQ(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldCurrentPlace, v))
}

// CurrentPlaceIn applies the In predicate on the "current_place" field.
func CurrentPlaceIn(vs ...int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldCurrentPlace, vs...))
}

// CurrentPlaceNotIn applies the NotIn predicate on the "current_place" field.
func CurrentPlaceNotIn(vs ...int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldCurrentPlace, vs...))
}

// CurrentPlaceGT applies the GT predicate on the "current_place" field.
func CurrentPlaceGT(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldCurrentPlace, v))
}

// CurrentPlaceGTE applies the GTE predicate on the "current_place" field.
func CurrentPlaceGTE(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldCurrentPlace, v))
}

// CurrentPlaceLT applies the LT predicate on the "current_place" field.
func CurrentPlaceLT(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldCurrentPlace, v))
}

// CurrentPlaceLTE applies the LTE predicate on the "current_place" field.
func CurrentPlaceLTE(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldCurrentPlace, v))
}

// PointsEQ applies the EQ predicate on the "points" field.
func PointsEQ(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldPoints, v))
}

// PointsNEQ applies the NEQ predicate on the "points" field.
func PointsNEQ(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldPoints, v))
}

// PointsIn applies the In predicate on the "points" field.
func PointsIn(vs ...float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldPoints, vs...))
}

// PointsNotIn applies the NotIn predicate on the "points" field.
func PointsNotIn(vs ...float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldPoints, vs...))
}

// PointsGT applies the GT predicate on the "points" field.
func PointsGT(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldPoints, v))
}

// PointsGTE applies the GTE predicate on the "points" field.
func PointsGTE(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldPoints, v))
}

// PointsLT applies the LT predicate on the "points" field.
func PointsLT(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldPoints, v))
}

// PointsLTE applies the LTE predicate on the "points" field.
func PointsLTE(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldPoints, v))
}

// PointsIsNil applies the IsNil predicate on the "points" field.
func PointsIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldPoints))
}

// PointsNotNil applies the NotNil predicate on the "points" field.
func PointsNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldPoints))
}

// AvgPlaceEQ applies the EQ predicate on the "avg_place" field.
func AvgPlaceEQ(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldAvgPlace, v))
}

// AvgPlaceNEQ applies the NEQ predicate on the "avg_place" field.
func AvgPlaceNEQ(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldAvgPlace, v))
}

// AvgPlaceIn applies the In predicate on the "avg_place" field.
func AvgPlaceIn(vs ...float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldAvgPlace, vs...))
}

// AvgPlaceNotIn applies the NotIn predicate on the "avg_place" field.
func AvgPlaceNotIn(vs ...float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldAvgPlace, vs...))
}

// AvgPlaceGT applies the GT predicate on the "avg_place" field.
func AvgPlaceGT(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldAvgPlace, v))
}

// AvgPlaceGTE applies the GTE predicate on the "avg_place" field.
func AvgPlaceGTE(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldAvgPlace, v))
}

// AvgPlaceLT applies the LT predicate on the "avg_place" field.
func AvgPlaceLT(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldAvgPlace, v))
}

// AvgPlaceLTE applies the LTE predicate on the "avg_place" field.
func AvgPlaceLTE(v float64) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldAvgPlace, v))
}

// AvgPlaceIsNil applies the IsNil predicate on the "avg_place" field.
func AvgPlaceIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldAvgPlace))
}

// AvgPlaceNotNil applies the NotNil predicate on the "avg_place" field.
func AvgPlaceNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldAvgPlace))
}

// YearsActiveEQ applies the EQ predicate on the "years_active" field.
func YearsActiveEQ(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldEQ(FieldYearsActive, v))
}

// YearsActiveNEQ applies the NEQ predicate on the "years_active" field.
func YearsActiveNEQ(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNEQ(FieldYearsActive, v))
}

// YearsActiveIn applies the In predicate on the "years_active" field.
func YearsActiveIn(vs ...int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIn(FieldYearsActive, vs...))
}

// YearsActiveNotIn applies the NotIn predicate on the "years_active" field.
func YearsActiveNotIn(vs ...int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotIn(FieldYearsActive, vs...))
}

// YearsActiveGT applies the GT predicate on the "years_active" field.
func YearsActiveGT(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGT(FieldYearsActive, v))
}

// YearsActiveGTE applies the GTE predicate on the "years_active" field.
func YearsActiveGTE(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldGTE(FieldYearsActive, v))
}

// YearsActiveLT applies the LT predicate on the "years_active" field.
func YearsActiveLT(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLT(FieldYearsActive, v))
}

// YearsActiveLTE applies the LTE predicate on the "years_active" field.
func YearsActiveLTE(v int) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldLTE(FieldYearsActive, v))
}

// ContestHistoryIsNil applies the IsNil predicate on the "contest_history" field.
func ContestHistoryIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldContestHistory))
}

// ContestHistoryNotNil applies the NotNil predicate on the "contest_history" field.
func ContestHistoryNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldContestHistory))
}

// AchievementsIsNil applies the IsNil predicate on the "achievements" field.
func AchievementsIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldAchievements))
}

// AchievementsNotNil applies the NotNil predicate on the "achievements" field.
func AchievementsNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldAchievements))
}

// MembersIsNil applies the IsNil predicate on the "members" field.
func MembersIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldMembers))
}

// MembersNotNil applies the NotNil predicate on the "members" field.
func MembersNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldMembers))
}

// CaptainIsNil applies the IsNil predicate on the "captain" field.
func CaptainIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldCaptain))
}

// CaptainNotNil applies the NotNil predicate on the "captain" field.
func CaptainNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldCaptain))
}

// VerifiedByIsNil applies the IsNil predicate on the "verified_by" field.
func VerifiedByIsNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldIsNull(FieldVerifiedBy))
}

// VerifiedByNotNil applies the NotNil predicate on the "verified_by" field.
func VerifiedByNotNil() predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.FieldNotNull(FieldVerifiedBy))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AggregatedTeamDetails) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AggregatedTeamDetails) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AggregatedTeamDetails) predicate.AggregatedTeamDetails {
	return predicate.AggregatedTeamDetails(sql.NotPredicates(p))
}
